name: Bug Report
description: Report a bug in ClawdStrike
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the form below.
        **Security vulnerabilities**: Please use [private reporting](https://github.com/backbay-labs/clawdstrike/security/advisories/new) instead.
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - "Guards / Policy Engine (crates/clawdstrike)"
        - "Crypto (crates/hush-core)"
        - "CLI (crates/hush-cli)"
        - "Daemon (crates/hushd)"
        - "Spine Protocol (crates/spine)"
        - "Tetragon Bridge (crates/tetragon-bridge)"
        - "Hubble Bridge (crates/hubble-bridge)"
        - "Desktop App (apps/desktop)"
        - "TypeScript SDK (packages/hush-ts)"
        - "Python SDK (packages/hush-py)"
        - "Rulesets"
        - "Documentation"
        - "Helm Chart / Deployment"
        - "Other"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Clear description of the bug
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Minimal steps to reproduce the behavior
      value: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        - OS:
        - Rust version:
        - ClawdStrike version:
      render: text
    validations:
      required: false
