/* Auto-generated by cbindgen. Do not edit. */

#ifndef HUSH_GO_NATIVE_H
#define HUSH_GO_NATIVE_H

#include <stdbool.h>
#include <stddef.h>

bool hush_is_available(void);

char *hush_sha256(const unsigned char *data, size_t len);

char *hush_keccak256(const unsigned char *data, size_t len);

bool hush_verify_ed25519(const unsigned char *msg,
                         size_t msg_len,
                         const char *sig_hex,
                         const char *pk_hex);

char *hush_canonicalize(const char *json_str);

char *hush_merkle_root(const char *leaves_json);

char *hush_generate_merkle_proof(const char *leaves_json, size_t index);

bool hush_verify_receipt(const char *receipt_json,
                         const char *sig_hex,
                         const char *pk_hex);

char *hush_detect_jailbreak(const char *text,
                            const char *session_id,
                            const char *config_json);

char *hush_sanitize_output(const char *text, const char *config_json);

char *hush_watermark_public_key(const char *config_json);

char *hush_watermark_prompt(const char *prompt,
                            const char *config_json,
                            const char *app_id,
                            const char *session_id);

char *hush_extract_watermark(const char *text, const char *config_json);

void hush_free_string(char *ptr);

#endif /* HUSH_GO_NATIVE_H */
