import Lake
open Lake DSL

package clawdstrike where
  leanOptions := #[
    ⟨`autoImplicit, false⟩
  ]

-- Aeneas standard library (for types generated by Aeneas)
require aeneas from git "https://github.com/AeneasVerif/aeneas" @ "main" / "backends" / "lean"

-- All code: hand-written spec/proofs + Aeneas-generated impl + Phase 3 bridge proofs
@[default_target]
lean_lib ClawdStrike where
  srcDir := "."
