/**
 * Static ruleset data module.
 *
 * Re-exports parsed JSON rulesets generated by `scripts/extract-rulesets.ts`.
 * Components import from here rather than reading YAML at runtime.
 */

// Individual rulesets (generated at build time)
import defaultRuleset from '@/data/rulesets/default.json';
import strictRuleset from '@/data/rulesets/strict.json';
import permissiveRuleset from '@/data/rulesets/permissive.json';
import aiAgentRuleset from '@/data/rulesets/ai-agent.json';
import aiAgentPostureRuleset from '@/data/rulesets/ai-agent-posture.json';
import cicdRuleset from '@/data/rulesets/cicd.json';
import remoteDesktopRuleset from '@/data/rulesets/remote-desktop.json';
import remoteDesktopStrictRuleset from '@/data/rulesets/remote-desktop-strict.json';
import remoteDesktopPermissiveRuleset from '@/data/rulesets/remote-desktop-permissive.json';
import spiderSenseRuleset from '@/data/rulesets/spider-sense.json';

// Index of all rulesets
import rulesetIndexData from '@/data/rulesets/index.json';

/** All 10 built-in ruleset names. */
export const RULESET_NAMES = [
  'default',
  'strict',
  'permissive',
  'ai-agent',
  'ai-agent-posture',
  'cicd',
  'remote-desktop',
  'remote-desktop-strict',
  'remote-desktop-permissive',
  'spider-sense',
] as const;

/** Type for a single entry in the ruleset index. */
export type RulesetIndexEntry = {
  name: string;
  extends?: string;
  description: string;
};

/** Parsed rulesets keyed by name. */
export const rulesets: Record<string, object> = {
  default: defaultRuleset,
  strict: strictRuleset,
  permissive: permissiveRuleset,
  'ai-agent': aiAgentRuleset,
  'ai-agent-posture': aiAgentPostureRuleset,
  cicd: cicdRuleset,
  'remote-desktop': remoteDesktopRuleset,
  'remote-desktop-strict': remoteDesktopStrictRuleset,
  'remote-desktop-permissive': remoteDesktopPermissiveRuleset,
  'spider-sense': spiderSenseRuleset,
};

/** Index of all rulesets with name, extends, and description. */
export const rulesetIndex = rulesetIndexData as Record<string, RulesetIndexEntry>;
