{{- $enableNats := and .Values.serviceMonitor.endpoints.nats .Values.nats.enabled .Values.nats.monitoring.enabled (not .Values.nats.external.enabled) }}
{{- $enableProofsApi := and .Values.serviceMonitor.endpoints.proofsApi .Values.spine.enabled .Values.spine.proofsApi.enabled }}
{{- $enableHushd := and .Values.serviceMonitor.endpoints.hushd .Values.hushd.enabled }}
{{- if and .Values.serviceMonitor.enabled (or $enableNats $enableProofsApi $enableHushd) }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "clawdstrike.fullname" . }}
  namespace: {{ include "clawdstrike.namespace" . }}
  labels:
    {{- include "clawdstrike.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/part-of: clawdstrike
  endpoints:
    {{- if $enableNats }}
    - port: monitoring
      interval: {{ .Values.serviceMonitor.interval }}
      path: /varz
    {{- end }}
    {{- if $enableProofsApi }}
    - port: http
      interval: {{ .Values.serviceMonitor.interval }}
      path: /metrics
    {{- end }}
    {{- if $enableHushd }}
    - port: http
      interval: {{ .Values.serviceMonitor.interval }}
      path: /metrics
    {{- end }}
{{- end }}
