-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [clawdstrike]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes.
import Aeneas
import Clawdstrike.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000
open clawdstrike

/-- [core::fmt::{core::fmt::Formatter<'a>}::debug_struct_field2_finish]:
    Source: '/rustc/library/core/src/fmt/mod.rs', lines 2466:4-2473:15
    Name pattern: [core::fmt::{core::fmt::Formatter<'a>}::debug_struct_field2_finish] -/
@[rust_fun "core::fmt::{core::fmt::Formatter<'a>}::debug_struct_field2_finish"]
axiom core.fmt.Formatter.debug_struct_field2_finish
  :
  core.fmt.Formatter → Str → Str → Dyn (fun _dyn => core.fmt.Debug _dyn)
    → Str → Dyn (fun _dyn => core.fmt.Debug _dyn) → Result
    ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)

/-- [core::fmt::{core::fmt::Formatter<'a>}::debug_struct_field5_finish]:
    Source: '/rustc/library/core/src/fmt/mod.rs', lines 2532:4-2545:15
    Name pattern: [core::fmt::{core::fmt::Formatter<'a>}::debug_struct_field5_finish] -/
@[rust_fun "core::fmt::{core::fmt::Formatter<'a>}::debug_struct_field5_finish"]
axiom core.fmt.Formatter.debug_struct_field5_finish
  :
  core.fmt.Formatter → Str → Str → Dyn (fun _dyn => core.fmt.Debug _dyn)
    → Str → Dyn (fun _dyn => core.fmt.Debug _dyn) → Str → Dyn (fun _dyn
    => core.fmt.Debug _dyn) → Str → Dyn (fun _dyn => core.fmt.Debug _dyn)
    → Str → Dyn (fun _dyn => core.fmt.Debug _dyn) → Result
    ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)

/-- [core::fmt::{core::fmt::Display for str}::fmt]:
    Source: '/rustc/library/core/src/fmt/mod.rs', lines 2959:4-2959:50
    Name pattern: [core::fmt::{core::fmt::Display<str>}::fmt] -/
@[rust_fun "core::fmt::{core::fmt::Display<str>}::fmt"]
axiom Str.Insts.CoreFmtDisplay.fmt
  :
  Str → core.fmt.Formatter → Result ((core.result.Result Unit
    core.fmt.Error) × core.fmt.Formatter)

/-- [core::hash::impls::{core::hash::Hash for isize}::hash]:
    Source: '/rustc/library/core/src/hash/mod.rs', lines 812:16-812:56
    Name pattern: [core::hash::impls::{core::hash::Hash<isize>}::hash] -/
@[rust_fun "core::hash::impls::{core::hash::Hash<isize>}::hash"]
axiom Isize.Insts.CoreHashHash.hash
  {H : Type} (HasherInst : core.hash.Hasher H) : Std.Isize → H → Result H

/-- [core::hash::impls::{core::hash::Hash for str}::hash]:
    Source: '/rustc/library/core/src/hash/mod.rs', lines 864:8-864:48
    Name pattern: [core::hash::impls::{core::hash::Hash<str>}::hash] -/
@[rust_fun "core::hash::impls::{core::hash::Hash<str>}::hash"]
axiom Str.Insts.CoreHashHash.hash
  {H : Type} (HasherInst : core.hash.Hasher H) : Str → H → Result H

/-- [core::iter::adapters::enumerate::{core::iter::traits::iterator::Iterator<(usize, Clause0_Item)> for core::iter::adapters::enumerate::Enumerate<I>}::next]:
    Source: '/rustc/library/core/src/iter/adapters/enumerate.rs', lines 79:4-79:64
    Name pattern: [core::iter::adapters::enumerate::{core::iter::traits::iterator::Iterator<core::iter::adapters::enumerate::Enumerate<@I>, (usize, @Clause0_Item)>}::next] -/
@[rust_fun
  "core::iter::adapters::enumerate::{core::iter::traits::iterator::Iterator<core::iter::adapters::enumerate::Enumerate<@I>, (usize, @Clause0_Item)>}::next"]
axiom
  core.iter.adapters.enumerate.Enumerate.Insts.CoreIterTraitsIteratorIteratorPairUsizeClause0_Item.next
  {I : Type} {Clause0_Item : Type} (traitsiteratorIteratorInst :
  core.iter.traits.iterator.Iterator I Clause0_Item) :
  core.iter.adapters.enumerate.Enumerate I → Result ((Option (Std.Usize ×
    Clause0_Item)) × (core.iter.adapters.enumerate.Enumerate I))

/-- [core::iter::adapters::enumerate::{core::iter::traits::iterator::Iterator<(usize, Clause0_Item)> for core::iter::adapters::enumerate::Enumerate<I>}::collect]:
    Source: '/rustc/library/core/src/iter/adapters/enumerate.rs', lines 62:0-64:16
    Name pattern: [core::iter::adapters::enumerate::{core::iter::traits::iterator::Iterator<core::iter::adapters::enumerate::Enumerate<@I>, (usize, @Clause0_Item)>}::collect] -/
@[rust_fun
  "core::iter::adapters::enumerate::{core::iter::traits::iterator::Iterator<core::iter::adapters::enumerate::Enumerate<@I>, (usize, @Clause0_Item)>}::collect"]
axiom
  core.iter.adapters.enumerate.Enumerate.Insts.CoreIterTraitsIteratorIteratorPairUsizeClause0_Item.collect
  {I : Type} {B : Type} {Clause0_Item : Type} (traitsiteratorIteratorInst :
  core.iter.traits.iterator.Iterator I Clause0_Item)
  (traitscollectFromIteratorBPairUsizeClause0_ItemInst :
  core.iter.traits.collect.FromIterator B (Std.Usize × Clause0_Item)) :
  core.iter.adapters.enumerate.Enumerate I → Result B

/-- [core::iter::adapters::enumerate::{core::iter::traits::iterator::Iterator<(usize, Clause0_Item)> for core::iter::adapters::enumerate::Enumerate<I>}::skip]:
    Source: '/rustc/library/core/src/iter/adapters/enumerate.rs', lines 62:0-64:16
    Name pattern: [core::iter::adapters::enumerate::{core::iter::traits::iterator::Iterator<core::iter::adapters::enumerate::Enumerate<@I>, (usize, @Clause0_Item)>}::skip] -/
@[rust_fun
  "core::iter::adapters::enumerate::{core::iter::traits::iterator::Iterator<core::iter::adapters::enumerate::Enumerate<@I>, (usize, @Clause0_Item)>}::skip"]
axiom
  core.iter.adapters.enumerate.Enumerate.Insts.CoreIterTraitsIteratorIteratorPairUsizeClause0_Item.skip
  {I : Type} {Clause0_Item : Type} (traitsiteratorIteratorInst :
  core.iter.traits.iterator.Iterator I Clause0_Item) :
  core.iter.adapters.enumerate.Enumerate I → Std.Usize → Result
    (core.iter.adapters.skip.Skip (core.iter.adapters.enumerate.Enumerate I))

/-- [core::iter::adapters::enumerate::{core::iter::traits::iterator::Iterator<(usize, Clause0_Item)> for core::iter::adapters::enumerate::Enumerate<I>}::enumerate]:
    Source: '/rustc/library/core/src/iter/adapters/enumerate.rs', lines 62:0-64:16
    Name pattern: [core::iter::adapters::enumerate::{core::iter::traits::iterator::Iterator<core::iter::adapters::enumerate::Enumerate<@I>, (usize, @Clause0_Item)>}::enumerate] -/
@[rust_fun
  "core::iter::adapters::enumerate::{core::iter::traits::iterator::Iterator<core::iter::adapters::enumerate::Enumerate<@I>, (usize, @Clause0_Item)>}::enumerate"]
axiom
  core.iter.adapters.enumerate.Enumerate.Insts.CoreIterTraitsIteratorIteratorPairUsizeClause0_Item.enumerate
  {I : Type} {Clause0_Item : Type} (traitsiteratorIteratorInst :
  core.iter.traits.iterator.Iterator I Clause0_Item) :
  core.iter.adapters.enumerate.Enumerate I → Result
    (core.iter.adapters.enumerate.Enumerate
    (core.iter.adapters.enumerate.Enumerate I))

/-- [core::iter::adapters::enumerate::{core::iter::traits::iterator::Iterator<(usize, Clause0_Item)> for core::iter::adapters::enumerate::Enumerate<I>}::map]:
    Source: '/rustc/library/core/src/iter/adapters/enumerate.rs', lines 62:0-64:16
    Name pattern: [core::iter::adapters::enumerate::{core::iter::traits::iterator::Iterator<core::iter::adapters::enumerate::Enumerate<@I>, (usize, @Clause0_Item)>}::map] -/
@[rust_fun
  "core::iter::adapters::enumerate::{core::iter::traits::iterator::Iterator<core::iter::adapters::enumerate::Enumerate<@I>, (usize, @Clause0_Item)>}::map"]
axiom
  core.iter.adapters.enumerate.Enumerate.Insts.CoreIterTraitsIteratorIteratorPairUsizeClause0_Item.map
  {I : Type} {B : Type} {F : Type} {Clause0_Item : Type}
  (traitsiteratorIteratorInst : core.iter.traits.iterator.Iterator I
  Clause0_Item) (opsfunctionFnMutFTuplePairUsizeClause0_ItemBInst :
  core.ops.function.FnMut F (Std.Usize × Clause0_Item) B) :
  core.iter.adapters.enumerate.Enumerate I → F → Result
    (core.iter.adapters.map.Map (core.iter.adapters.enumerate.Enumerate I) F)

/-- [core::iter::adapters::map::{core::iter::traits::iterator::Iterator<B> for core::iter::adapters::map::Map<I, F>}::collect]:
    Source: '/rustc/library/core/src/iter/adapters/map.rs', lines 99:0-101:27
    Name pattern: [core::iter::adapters::map::{core::iter::traits::iterator::Iterator<core::iter::adapters::map::Map<@I, @F>, @B>}::collect] -/
@[rust_fun
  "core::iter::adapters::map::{core::iter::traits::iterator::Iterator<core::iter::adapters::map::Map<@I, @F>, @B>}::collect"]
axiom core.iter.adapters.map.Map.Insts.CoreIterTraitsIteratorIterator.collect
  {B : Type} {I : Type} {F : Type} {B1 : Type} {Clause0_Item : Type}
  (traitsiteratorIteratorInst : core.iter.traits.iterator.Iterator I
  Clause0_Item) (opsfunctionFnMutFTupleClause0_ItemBInst :
  core.ops.function.FnMut F Clause0_Item B) (traitscollectFromIteratorInst :
  core.iter.traits.collect.FromIterator B1 B) :
  core.iter.adapters.map.Map I F → Result B1

/-- [core::iter::adapters::skip::{core::iter::traits::iterator::Iterator<Clause0_Item> for core::iter::adapters::skip::Skip<I>}::next]:
    Source: '/rustc/library/core/src/iter/adapters/skip.rs', lines 40:4-40:41
    Name pattern: [core::iter::adapters::skip::{core::iter::traits::iterator::Iterator<core::iter::adapters::skip::Skip<@I>, @Clause0_Item>}::next] -/
@[rust_fun
  "core::iter::adapters::skip::{core::iter::traits::iterator::Iterator<core::iter::adapters::skip::Skip<@I>, @Clause0_Item>}::next"]
axiom core.iter.adapters.skip.Skip.Insts.CoreIterTraitsIteratorIterator.next
  {I : Type} {Clause0_Item : Type} (traitsiteratorIteratorInst :
  core.iter.traits.iterator.Iterator I Clause0_Item) :
  core.iter.adapters.skip.Skip I → Result ((Option Clause0_Item) ×
    (core.iter.adapters.skip.Skip I))

/-- [core::iter::traits::iterator::Iterator::map]:
    Source: '/rustc/library/core/src/iter/traits/iterator.rs', lines 789:4-792:34
    Name pattern: [core::iter::traits::iterator::Iterator::map] -/
@[rust_fun "core::iter::traits::iterator::Iterator::map"]
axiom core.iter.traits.iterator.Iterator.map.default
  {Self : Type} {B : Type} {F : Type} {Clause0_Item : Type} (IteratorInst :
  core.iter.traits.iterator.Iterator Self Clause0_Item)
  (opsfunctionFnMutFTupleClause0_ItemBInst : core.ops.function.FnMut F
  Clause0_Item B) :
  Self → F → Result (core.iter.adapters.map.Map Self F)

/-- [core::iter::traits::iterator::Iterator::enumerate]:
    Source: '/rustc/library/core/src/iter/traits/iterator.rs', lines 1005:4-1007:20
    Name pattern: [core::iter::traits::iterator::Iterator::enumerate] -/
@[rust_fun "core::iter::traits::iterator::Iterator::enumerate"]
axiom core.iter.traits.iterator.Iterator.enumerate.default
  {Self : Type} {Clause0_Item : Type} (IteratorInst :
  core.iter.traits.iterator.Iterator Self Clause0_Item) :
  Self → Result (core.iter.adapters.enumerate.Enumerate Self)

/-- [core::iter::traits::iterator::Iterator::skip]:
    Source: '/rustc/library/core/src/iter/traits/iterator.rs', lines 1341:4-1343:20
    Name pattern: [core::iter::traits::iterator::Iterator::skip] -/
@[rust_fun "core::iter::traits::iterator::Iterator::skip"]
axiom core.iter.traits.iterator.Iterator.skip.default
  {Self : Type} {Clause0_Item : Type} (IteratorInst :
  core.iter.traits.iterator.Iterator Self Clause0_Item) :
  Self → Std.Usize → Result (core.iter.adapters.skip.Skip Self)

/-- [core::option::{core::option::Option<T>}::or]:
    Source: '/rustc/library/core/src/option.rs', lines 1621:4-1623:28
    Name pattern: [core::option::{core::option::Option<@T>}::or] -/
@[rust_fun "core::option::{core::option::Option<@T>}::or"]
axiom core.option.Option.or
  {T : Type} : Option T → Option T → Result (Option T)

/-- [core::option::{core::option::Option<T>}::or_else]:
    Source: '/rustc/library/core/src/option.rs', lines 1647:4-1652:28
    Name pattern: [core::option::{core::option::Option<@T>}::or_else] -/
@[rust_fun "core::option::{core::option::Option<@T>}::or_else"]
axiom core.option.Option.or_else
  {T : Type} {F : Type} (opsfunctionFnOnceFTupleOptionInst :
  core.ops.function.FnOnce F Unit (Option T)) :
  Option T → F → Result (Option T)

/-- [core::option::{core::clone::Clone for core::option::Option<T>}::clone]:
    Source: '/rustc/library/core/src/option.rs', lines 2261:4-2261:27
    Name pattern: [core::option::{core::clone::Clone<core::option::Option<@T>>}::clone] -/
@[rust_fun
  "core::option::{core::clone::Clone<core::option::Option<@T>>}::clone"]
axiom core.option.Option.Insts.CoreCloneClone.clone
  {T : Type} (cloneCloneInst : core.clone.Clone T) :
  Option T → Result (Option T)

/-- [core::slice::iter::{core::iter::traits::iterator::Iterator<&'a (T)> for core::slice::iter::Iter<'a, T>}::collect]:
    Source: '/rustc/library/core/src/slice/iter/macros.rs', lines 153:8-153:45
    Name pattern: [core::slice::iter::{core::iter::traits::iterator::Iterator<core::slice::iter::Iter<'a, @T>, &'a @T>}::collect] -/
@[rust_fun
  "core::slice::iter::{core::iter::traits::iterator::Iterator<core::slice::iter::Iter<'a, @T>, &'a @T>}::collect"]
axiom core.slice.iter.Iter.Insts.CoreIterTraitsIteratorIteratorSharedAT.collect
  {T : Type} {B : Type} (itertraitscollectFromIteratorBSharedATInst :
  core.iter.traits.collect.FromIterator B T) :
  core.slice.iter.Iter T → Result B

/-- [core::slice::iter::{core::iter::traits::iterator::Iterator<&'a (T)> for core::slice::iter::Iter<'a, T>}::skip]:
    Source: '/rustc/library/core/src/slice/iter/macros.rs', lines 153:8-153:45
    Name pattern: [core::slice::iter::{core::iter::traits::iterator::Iterator<core::slice::iter::Iter<'a, @T>, &'a @T>}::skip] -/
@[rust_fun
  "core::slice::iter::{core::iter::traits::iterator::Iterator<core::slice::iter::Iter<'a, @T>, &'a @T>}::skip"]
axiom core.slice.iter.Iter.Insts.CoreIterTraitsIteratorIteratorSharedAT.skip
  {T : Type} :
  core.slice.iter.Iter T → Std.Usize → Result (core.iter.adapters.skip.Skip
    (core.slice.iter.Iter T))

/-- [core::slice::iter::{core::iter::traits::iterator::Iterator<&'a (T)> for core::slice::iter::Iter<'a, T>}::map]:
    Source: '/rustc/library/core/src/slice/iter/macros.rs', lines 153:8-153:45
    Name pattern: [core::slice::iter::{core::iter::traits::iterator::Iterator<core::slice::iter::Iter<'a, @T>, &'a @T>}::map] -/
@[rust_fun
  "core::slice::iter::{core::iter::traits::iterator::Iterator<core::slice::iter::Iter<'a, @T>, &'a @T>}::map"]
axiom core.slice.iter.Iter.Insts.CoreIterTraitsIteratorIteratorSharedAT.map
  {T : Type} {B : Type} {F : Type} (opsfunctionFnMutFTupleSharedATBInst :
  core.ops.function.FnMut F T B) :
  core.slice.iter.Iter T → F → Result (core.iter.adapters.map.Map
    (core.slice.iter.Iter T) F)

/-- [core::str::{str}::is_empty]:
    Source: '/rustc/library/core/src/str/mod.rs', lines 161:4-161:40
    Name pattern: [core::str::{str}::is_empty] -/
@[rust_fun "core::str::{str}::is_empty"]
axiom core.str.Str.is_empty : Str → Result Bool

/-- [core::str::traits::{core::cmp::PartialEq<str> for str}::eq]:
    Source: '/rustc/library/core/src/str/traits.rs', lines 29:4-29:37
    Name pattern: [core::str::traits::{core::cmp::PartialEq<str, str>}::eq] -/
@[rust_fun "core::str::traits::{core::cmp::PartialEq<str, str>}::eq"]
axiom Str.Insts.CoreCmpPartialEqStr.eq : Str → Str → Result Bool

/-- [core::str::traits::{core::cmp::Eq for str}::assert_receiver_is_total_eq]:
    Source: '/rustc/library/core/src/str/traits.rs', lines 36:0-36:21
    Name pattern: [core::str::traits::{core::cmp::Eq<str>}::assert_receiver_is_total_eq] -/
@[rust_fun
  "core::str::traits::{core::cmp::Eq<str>}::assert_receiver_is_total_eq"]
axiom Str.Insts.CoreCmpEq.assert_receiver_is_total_eq : Str → Result Unit

/-- [std::collections::hash::set::{std::collections::hash::set::HashSet<T, S, A>}::contains]:
    Source: '/rustc/library/std/src/collections/hash/set.rs', lines 767:4-770:21
    Name pattern: [std::collections::hash::set::{std::collections::hash::set::HashSet<@T, @S, @A>}::contains] -/
@[rust_fun
  "std::collections::hash::set::{std::collections::hash::set::HashSet<@T, @S, @A>}::contains"]
axiom std.collections.hash.set.HashSet.contains
  {T : Type} {S : Type} {A : Type} {Q : Type} {Clause2_Hasher : Type}
  (corecmpEqInst : core.cmp.Eq T) (corehashHashInst : core.hash.Hash T)
  (corehashBuildHasherInst : core.hash.BuildHasher S Clause2_Hasher)
  (coreborrowBorrowInst : core.borrow.Borrow T Q) (corehashHashInst1 :
  core.hash.Hash Q) (corecmpEqInst1 : core.cmp.Eq Q) :
  std.collections.hash.set.HashSet T S A → Q → Result Bool

/-- [std::hash::random::{core::hash::Hasher for std::hash::random::DefaultHasher}::finish]:
    Source: '/rustc/library/std/src/hash/random.rs', lines 140:4-140:27
    Name pattern: [std::hash::random::{core::hash::Hasher<std::hash::random::DefaultHasher>}::finish] -/
@[rust_fun
  "std::hash::random::{core::hash::Hasher<std::hash::random::DefaultHasher>}::finish"]
axiom std.hash.random.DefaultHasher.Insts.CoreHashHasher.finish
  : std.hash.random.DefaultHasher → Result Std.U64

/-- [std::hash::random::{core::hash::Hasher for std::hash::random::DefaultHasher}::write]:
    Source: '/rustc/library/std/src/hash/random.rs', lines 130:4-130:35
    Name pattern: [std::hash::random::{core::hash::Hasher<std::hash::random::DefaultHasher>}::write] -/
@[rust_fun
  "std::hash::random::{core::hash::Hasher<std::hash::random::DefaultHasher>}::write"]
axiom std.hash.random.DefaultHasher.Insts.CoreHashHasher.write
  :
  std.hash.random.DefaultHasher → Slice Std.U8 → Result
    std.hash.random.DefaultHasher

/-- [std::hash::random::{core::hash::BuildHasher<std::hash::random::DefaultHasher> for std::hash::random::RandomState}::build_hasher]:
    Source: '/rustc/library/std/src/hash/random.rs', lines 83:4-83:43
    Name pattern: [std::hash::random::{core::hash::BuildHasher<std::hash::random::RandomState, std::hash::random::DefaultHasher>}::build_hasher] -/
@[rust_fun
  "std::hash::random::{core::hash::BuildHasher<std::hash::random::RandomState, std::hash::random::DefaultHasher>}::build_hasher"]
axiom
  std.hash.random.RandomState.Insts.CoreHashBuildHasherDefaultHasher.build_hasher
  : std.hash.random.RandomState → Result std.hash.random.DefaultHasher

/-- [alloc::str::{core::borrow::Borrow<str> for alloc::string::String}::borrow]:
    Source: '/rustc/library/alloc/src/str.rs', lines 191:4-191:28
    Name pattern: [alloc::str::{core::borrow::Borrow<alloc::string::String, str>}::borrow] -/
@[rust_fun
  "alloc::str::{core::borrow::Borrow<alloc::string::String, str>}::borrow"]
axiom alloc.string.String.Insts.CoreBorrowBorrowStr.borrow
  : String → Result Str

/-- [alloc::string::{core::cmp::PartialEq<alloc::string::String> for alloc::string::String}::eq]:
    Source: '/rustc/library/alloc/src/string.rs', lines 350:9-350:18
    Name pattern: [alloc::string::{core::cmp::PartialEq<alloc::string::String, alloc::string::String>}::eq] -/
@[rust_fun
  "alloc::string::{core::cmp::PartialEq<alloc::string::String, alloc::string::String>}::eq"]
axiom alloc.string.String.Insts.CoreCmpPartialEqString.eq
  : String → String → Result Bool

/-- [alloc::string::{core::cmp::Eq for alloc::string::String}::assert_receiver_is_total_eq]:
    Source: '/rustc/library/alloc/src/string.rs', lines 350:32-350:34
    Name pattern: [alloc::string::{core::cmp::Eq<alloc::string::String>}::assert_receiver_is_total_eq] -/
@[rust_fun
  "alloc::string::{core::cmp::Eq<alloc::string::String>}::assert_receiver_is_total_eq"]
axiom alloc.string.String.Insts.CoreCmpEq.assert_receiver_is_total_eq
  : String → Result Unit

/-- [alloc::string::{core::clone::Clone for alloc::string::String}::clone]:
    Source: '/rustc/library/alloc/src/string.rs', lines 2351:4-2351:27
    Name pattern: [alloc::string::{core::clone::Clone<alloc::string::String>}::clone] -/
@[rust_fun "alloc::string::{core::clone::Clone<alloc::string::String>}::clone"]
axiom alloc.string.String.Insts.CoreCloneClone.clone : String → Result String

/-- [alloc::string::{core::cmp::PartialEq<&'a (str)> for alloc::string::String}::eq]:
    Source: '/rustc/library/alloc/src/string.rs', lines 2667:12-2667:46
    Name pattern: [alloc::string::{core::cmp::PartialEq<alloc::string::String, &'a str>}::eq] -/
@[rust_fun
  "alloc::string::{core::cmp::PartialEq<alloc::string::String, &'a str>}::eq"]
axiom alloc.string.String.Insts.CoreCmpPartialEqSharedAStr.eq
  : String → Str → Result Bool

/-- [alloc::string::{core::fmt::Debug for alloc::string::String}::fmt]:
    Source: '/rustc/library/alloc/src/string.rs', lines 2721:4-2721:60
    Name pattern: [alloc::string::{core::fmt::Debug<alloc::string::String>}::fmt] -/
@[rust_fun "alloc::string::{core::fmt::Debug<alloc::string::String>}::fmt"]
axiom alloc.string.String.Insts.CoreFmtDebug.fmt
  :
  String → core.fmt.Formatter → Result ((core.result.Result Unit
    core.fmt.Error) × core.fmt.Formatter)

/-- [alloc::string::{core::hash::Hash for alloc::string::String}::hash]:
    Source: '/rustc/library/alloc/src/string.rs', lines 2729:4-2729:51
    Name pattern: [alloc::string::{core::hash::Hash<alloc::string::String>}::hash] -/
@[rust_fun "alloc::string::{core::hash::Hash<alloc::string::String>}::hash"]
axiom alloc.string.String.Insts.CoreHashHash.hash
  {H : Type} (corehashHasherInst : core.hash.Hasher H) :
  String → H → Result H

/-- [alloc::string::{core::ops::deref::Deref<str> for alloc::string::String}::deref]:
    Source: '/rustc/library/alloc/src/string.rs', lines 2824:4-2824:27
    Name pattern: [alloc::string::{core::ops::deref::Deref<alloc::string::String, str>}::deref] -/
@[rust_fun
  "alloc::string::{core::ops::deref::Deref<alloc::string::String, str>}::deref"]
axiom alloc.string.String.Insts.CoreOpsDerefDerefStr.deref
  : String → Result Str

/-- [alloc::string::{alloc::string::ToString for T}::to_string]:
    Source: '/rustc/library/alloc/src/string.rs', lines 2895:4-2895:33
    Name pattern: [alloc::string::{alloc::string::ToString<@T>}::to_string] -/
@[rust_fun "alloc::string::{alloc::string::ToString<@T>}::to_string"]
axiom alloc.string.ToString.Blanket.to_string
  {T : Type} (corefmtDisplayInst : core.fmt.Display T) : T → Result String

/-- [alloc::string::{core::convert::From<&0 (str)> for alloc::string::String}::from]:
    Source: '/rustc/library/alloc/src/string.rs', lines 3115:4-3115:30
    Name pattern: [alloc::string::{core::convert::From<alloc::string::String, &'0 str>}::from] -/
@[rust_fun
  "alloc::string::{core::convert::From<alloc::string::String, &'0 str>}::from"]
axiom alloc.string.String.Insts.CoreConvertFromShared0Str.from
  : Str → Result String

