-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [clawdstrike]: type definitions
import Aeneas
import Clawdstrike.TypesExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

namespace clawdstrike

/-- Trait declaration: [core::borrow::Borrow]
    Source: '/rustc/library/core/src/borrow.rs', lines 158:0-158:40
    Name pattern: [core::borrow::Borrow] -/
@[rust_trait "core::borrow::Borrow"]
structure core.borrow.Borrow (Self : Type) (Borrowed : Type) where
  borrow : Self → Result Borrowed

/-- Trait declaration: [core::hash::BuildHasher]
    Source: '/rustc/library/core/src/hash/mod.rs', lines 637:0-637:21
    Name pattern: [core::hash::BuildHasher] -/
@[rust_trait "core::hash::BuildHasher" (parentClauses := ["HasherInst"])]
structure core.hash.BuildHasher (Self : Type) (Self_Hasher : Type) where
  HasherInst : core.hash.Hasher Self_Hasher
  build_hasher : Self → Result Self_Hasher

/-- [clawdstrike::core::verdict::CoreSeverity]
    Source: 'crates/libs/clawdstrike/src/core/verdict.rs', lines 5:0-14:1 -/
@[discriminant isize]
inductive core.verdict.CoreSeverity where
| Info : core.verdict.CoreSeverity
| Warning : core.verdict.CoreSeverity
| Error : core.verdict.CoreSeverity
| Critical : core.verdict.CoreSeverity

/-- [clawdstrike::core::verdict::CoreVerdict]
    Source: 'crates/libs/clawdstrike/src/core/verdict.rs', lines 31:0-37:1 -/
structure core.verdict.CoreVerdict where
  allowed : Bool
  severity : core.verdict.CoreSeverity
  sanitized : Bool
  guard : String
  message : String

/-- [clawdstrike::core::aggregate::aggregate_overall::closure]
    Source: 'crates/libs/clawdstrike/src/core/aggregate.rs', lines 63:13-63:53 -/
@[reducible]
def core.aggregate.aggregate_overall.closure := Unit

/-- [clawdstrike::core::cycle::CycleCheckResult]
    Source: 'crates/libs/clawdstrike/src/core/cycle.rs', lines 8:0-12:1 -/
@[discriminant isize]
inductive core.cycle.CycleCheckResult where
| Ok : core.cycle.CycleCheckResult
| DepthExceeded : Std.Usize → Std.Usize → core.cycle.CycleCheckResult
| CycleDetected : String → core.cycle.CycleCheckResult

/-- [clawdstrike::core::merge::CoreMergeStrategy]
    Source: 'crates/libs/clawdstrike/src/core/merge.rs', lines 5:0-12:1 -/
@[discriminant isize]
inductive core.merge.CoreMergeStrategy where
| Replace : core.merge.CoreMergeStrategy
| Merge : core.merge.CoreMergeStrategy
| DeepMerge : core.merge.CoreMergeStrategy

/-- [clawdstrike::core::merge::child_overrides::closure]
    Source: 'crates/libs/clawdstrike/src/core/merge.rs', lines 18:26-18:41 -/
@[reducible]
def core.merge.child_overrides.closure {T : Type} (corecloneCloneInst :
  core.clone.Clone T) :=
  Option T

end clawdstrike
