-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [hush_core]: function definitions
import Aeneas
import HushCore.Types
import HushCore.FunsExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace hush_core

/-- Trait implementation: [serde_core::de::ignored_any::{serde_core::de::Deserialize<'de> for serde_core::de::ignored_any::IgnoredAny}]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/serde_core-1.0.228/src/de/ignored_any.rs', lines 230:0-230:41
    Name pattern: [serde_core::de::Deserialize<'de, serde_core::de::ignored_any::IgnoredAny>] -/
@[reducible, rust_trait_impl
  "serde_core::de::Deserialize<'de, serde_core::de::ignored_any::IgnoredAny>"]
def serde_core.de.ignored_any.IgnoredAny.Insts.Serde_coreDeDeserialize :
  serde_core.de.Deserialize serde_core.de.ignored_any.IgnoredAny := {
  deserialize := fun {D : Type} {Clause0_Error : Type} (DeserializerInst :
    serde_core.de.Deserializer D Clause0_Error) =>
    serde_core.de.ignored_any.IgnoredAny.Insts.Serde_coreDeDeserialize.deserialize
    DeserializerInst
}

/-- Trait implementation: [serde_core::de::impls::{serde_core::de::Deserialize<'de> for usize}]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/serde_core-1.0.228/src/de/impls.rs', lines 130:8-130:49
    Name pattern: [serde_core::de::Deserialize<'de, usize>] -/
@[reducible, rust_trait_impl "serde_core::de::Deserialize<'de, usize>"]
def Usize.Insts.Serde_coreDeDeserialize : serde_core.de.Deserialize Std.Usize
  := {
  deserialize := fun {D : Type} {Clause0_Error : Type} (DeserializerInst :
    serde_core.de.Deserializer D Clause0_Error) =>
    Usize.Insts.Serde_coreDeDeserialize.deserialize DeserializerInst
}

/-- Trait implementation: [serde_core::de::impls::{serde_core::de::Deserialize<'de> for alloc::vec::Vec<T>}]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/serde_core-1.0.228/src/de/impls.rs', lines 1135:0-1137:24
    Name pattern: [serde_core::de::Deserialize<'de, alloc::vec::Vec<@T>>] -/
@[reducible, rust_trait_impl
  "serde_core::de::Deserialize<'de, alloc::vec::Vec<@T>>"]
def alloc.vec.Vec.Insts.Serde_coreDeDeserialize {T : Type} (DeserializeInst :
  serde_core.de.Deserialize T) : serde_core.de.Deserialize (alloc.vec.Vec T)
  := {
  deserialize := fun {D : Type} {Clause0_Error : Type} (DeserializerInst :
    serde_core.de.Deserializer D Clause0_Error) =>
    alloc.vec.Vec.Insts.Serde_coreDeDeserialize.deserialize DeserializeInst
    DeserializerInst
}

/-- Trait implementation: [serde_core::de::{serde_core::de::Expected for &0 (str)}]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/serde_core-1.0.228/src/de/mod.rs', lines 499:0-499:22
    Name pattern: [serde_core::de::Expected<&'0 str>] -/
@[reducible, rust_trait_impl "serde_core::de::Expected<&'0 str>"]
def Shared0Str.Insts.Serde_coreDeExpected : serde_core.de.Expected Str := {
  fmt := Shared0Str.Insts.Serde_coreDeExpected.fmt
}

/-- Trait implementation: [serde_core::ser::impls::{serde_core::ser::Serialize for usize}]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/serde_core-1.0.228/src/ser/impls.rs', lines 9:8-9:30
    Name pattern: [serde_core::ser::Serialize<usize>] -/
@[reducible, rust_trait_impl "serde_core::ser::Serialize<usize>"]
def Usize.Insts.Serde_coreSerSerialize : serde_core.ser.Serialize Std.Usize
  := {
  serialize := fun {S : Type} {Clause0_Ok : Type} {Clause0_Error : Type}
    {Clause0_SerializeSeq : Type} {Clause0_SerializeTuple : Type}
    {Clause0_SerializeTupleStruct : Type} {Clause0_SerializeTupleVariant :
    Type} {Clause0_SerializeMap : Type} {Clause0_SerializeStruct : Type}
    {Clause0_SerializeStructVariant : Type} (SerializerInst :
    serde_core.ser.Serializer S Clause0_Ok Clause0_Error Clause0_SerializeSeq
    Clause0_SerializeTuple Clause0_SerializeTupleStruct
    Clause0_SerializeTupleVariant Clause0_SerializeMap Clause0_SerializeStruct
    Clause0_SerializeStructVariant) =>
    Usize.Insts.Serde_coreSerSerialize.serialize SerializerInst
}

/-- Trait implementation: [serde_core::ser::impls::{serde_core::ser::Serialize for alloc::vec::Vec<T>}]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/serde_core-1.0.228/src/ser/impls.rs', lines 194:8-196:25
    Name pattern: [serde_core::ser::Serialize<alloc::vec::Vec<@T>>] -/
@[reducible, rust_trait_impl "serde_core::ser::Serialize<alloc::vec::Vec<@T>>"]
def alloc.vec.Vec.Insts.Serde_coreSerSerialize {T : Type} (SerializeInst :
  serde_core.ser.Serialize T) : serde_core.ser.Serialize (alloc.vec.Vec T) := {
  serialize := fun {S : Type} {Clause0_Ok : Type} {Clause0_Error : Type}
    {Clause0_SerializeSeq : Type} {Clause0_SerializeTuple : Type}
    {Clause0_SerializeTupleStruct : Type} {Clause0_SerializeTupleVariant :
    Type} {Clause0_SerializeMap : Type} {Clause0_SerializeStruct : Type}
    {Clause0_SerializeStructVariant : Type} (SerializerInst :
    serde_core.ser.Serializer S Clause0_Ok Clause0_Error Clause0_SerializeSeq
    Clause0_SerializeTuple Clause0_SerializeTupleStruct
    Clause0_SerializeTupleVariant Clause0_SerializeMap Clause0_SerializeStruct
    Clause0_SerializeStructVariant) =>
    alloc.vec.Vec.Insts.Serde_coreSerSerialize.serialize SerializeInst
    SerializerInst
}

/-- Trait implementation: [hush_core::hashing::{core::clone::Clone for hush_core::hashing::Hash}]
    Source: 'crates/libs/hush-core/src/hashing.rs', lines 10:9-10:14 -/
@[reducible]
def hashing.Hash.Insts.CoreCloneClone : core.clone.Clone hashing.Hash := {
  clone := hashing.Hash.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [hush_core::hashing::{core::fmt::Debug for hush_core::hashing::Hash}]
    Source: 'crates/libs/hush-core/src/hashing.rs', lines 10:22-10:27 -/
@[reducible]
def hashing.Hash.Insts.CoreFmtDebug : core.fmt.Debug hashing.Hash := {
  fmt := hashing.Hash.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [hush_core::hashing::{core::cmp::PartialEq<hush_core::hashing::Hash> for hush_core::hashing::Hash}]
    Source: 'crates/libs/hush-core/src/hashing.rs', lines 10:29-10:38 -/
@[reducible]
def hashing.Hash.Insts.CoreCmpPartialEqHash : core.cmp.PartialEq hashing.Hash
  hashing.Hash := {
  eq := hashing.Hash.Insts.CoreCmpPartialEqHash.eq
}

/-- Trait implementation: [hush_core::hashing::_::{serde_core::ser::Serialize for hush_core::hashing::Hash}]
    Source: 'crates/libs/hush-core/src/hashing.rs', lines 10:50-10:59 -/
@[reducible]
def hashing.Hash.Insts.Serde_coreSerSerialize : serde_core.ser.Serialize
  hashing.Hash := {
  serialize := fun {__S : Type} {Clause0_Ok : Type} {Clause0_Error : Type}
    {Clause0_SerializeSeq : Type} {Clause0_SerializeTuple : Type}
    {Clause0_SerializeTupleStruct : Type} {Clause0_SerializeTupleVariant :
    Type} {Clause0_SerializeMap : Type} {Clause0_SerializeStruct : Type}
    {Clause0_SerializeStructVariant : Type} (serde_coreserSerializerInst :
    serde_core.ser.Serializer __S Clause0_Ok Clause0_Error Clause0_SerializeSeq
    Clause0_SerializeTuple Clause0_SerializeTupleStruct
    Clause0_SerializeTupleVariant Clause0_SerializeMap Clause0_SerializeStruct
    Clause0_SerializeStructVariant) =>
    hashing.Hash.Insts.Serde_coreSerSerialize.serialize
    serde_coreserSerializerInst
}

/-- Trait implementation: [hush_core::hashing::_#1::{serde_core::de::Deserialize<'de> for hush_core::hashing::Hash}]
    Source: 'crates/libs/hush-core/src/hashing.rs', lines 10:61-10:72 -/
@[reducible]
def hashing.Hash.Insts.Serde_coreDeDeserialize : serde_core.de.Deserialize
  hashing.Hash := {
  deserialize := fun {__D : Type} {Clause0_Error : Type}
    (serde_coredeDeserializerInst : serde_core.de.Deserializer __D
    Clause0_Error) => hashing.Hash.Insts.Serde_coreDeDeserialize.deserialize
    serde_coredeDeserializerInst
}

/-- [hush_core::merkle::{core::clone::Clone for hush_core::merkle::MerkleTree}::clone]:
    Source: 'crates/libs/hush-core/src/merkle.rs', lines 52:9-52:14 -/
def merkle.MerkleTree.Insts.CoreCloneClone.clone
  (self : merkle.MerkleTree) : Result merkle.MerkleTree := do
  let v ←
    alloc.vec.CloneVec.clone (core.clone.CloneallocvecVec
      hashing.Hash.Insts.CoreCloneClone) self.levels
  ok { levels := v }

/-- Trait implementation: [hush_core::merkle::{core::clone::Clone for hush_core::merkle::MerkleTree}]
    Source: 'crates/libs/hush-core/src/merkle.rs', lines 52:9-52:14 -/
@[reducible]
def merkle.MerkleTree.Insts.CoreCloneClone : core.clone.Clone merkle.MerkleTree
  := {
  clone := merkle.MerkleTree.Insts.CoreCloneClone.clone
}

/-- [hush_core::merkle::{core::fmt::Debug for hush_core::merkle::MerkleTree}::fmt]:
    Source: 'crates/libs/hush-core/src/merkle.rs', lines 52:16-52:21 -/
def merkle.MerkleTree.Insts.CoreFmtDebug.fmt
  (self : merkle.MerkleTree) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn :=
    Dyn.mk _ (core.fmt.DebugShared (core.fmt.DebugVec (core.fmt.DebugVec
      hashing.Hash.Insts.CoreFmtDebug))) self.levels
  core.fmt.Formatter.debug_struct_field1_finish f (toStr "MerkleTree") (toStr
    "levels") dyn

/-- Trait implementation: [hush_core::merkle::{core::fmt::Debug for hush_core::merkle::MerkleTree}]
    Source: 'crates/libs/hush-core/src/merkle.rs', lines 52:16-52:21 -/
@[reducible]
def merkle.MerkleTree.Insts.CoreFmtDebug : core.fmt.Debug merkle.MerkleTree
  := {
  fmt := merkle.MerkleTree.Insts.CoreFmtDebug.fmt
}

/-- [hush_core::merkle::{hush_core::merkle::MerkleTree}::from_leaves]: loop body 0:
    Source: 'crates/libs/hush-core/src/merkle.rs', lines 77:8-80:9 -/
@[rust_loop_body]
def merkle.MerkleTree.from_leaves_loop0.body
  {T : Type} (coreconvertAsRefTSliceU8Inst : core.convert.AsRef T (Slice
  Std.U8)) (leaves : Slice T) (current : alloc.vec.Vec hashing.Hash)
  (li : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec hashing.Hash) × Std.Usize)
    (alloc.vec.Vec hashing.Hash))
  := do
  let i := Slice.len leaves
  if li < i
  then
    let t ← Slice.index_usize leaves li
    let s ← coreconvertAsRefTSliceU8Inst.as_ref t
    let h ← merkle.leaf_hash s
    let current1 ← alloc.vec.Vec.push current h
    let li1 ← li + 1#usize
    ok (cont (current1, li1))
  else ok (done current)

/-- [hush_core::merkle::{hush_core::merkle::MerkleTree}::from_leaves]: loop 0:
    Source: 'crates/libs/hush-core/src/merkle.rs', lines 77:8-80:9 -/
@[rust_loop]
def merkle.MerkleTree.from_leaves_loop0
  {T : Type} (coreconvertAsRefTSliceU8Inst : core.convert.AsRef T (Slice
  Std.U8)) (leaves : Slice T) (current : alloc.vec.Vec hashing.Hash)
  (li : Std.Usize) :
  Result (alloc.vec.Vec hashing.Hash)
  := do
  loop
    (fun (current1, li1) => merkle.MerkleTree.from_leaves_loop0.body
      coreconvertAsRefTSliceU8Inst leaves current1 li1)
    (current, li)

/-- [hush_core::merkle::{hush_core::merkle::MerkleTree}::from_leaves]: loop body 2:
    Source: 'crates/libs/hush-core/src/merkle.rs', lines 86:12-94:13 -/
@[rust_loop_body]
def merkle.MerkleTree.from_leaves_loop1_loop0.body
  (current : alloc.vec.Vec hashing.Hash) (next : alloc.vec.Vec hashing.Hash)
  (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec hashing.Hash) × Std.Usize)
    (alloc.vec.Vec hashing.Hash))
  := do
  let i1 := alloc.vec.Vec.len current
  if i < i1
  then
    let i2 ← i + 1#usize
    let i3 := alloc.vec.Vec.len current
    let next1 ←
      if i2 < i3
      then
        let h ←
          alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice
            hashing.Hash) current i
        let h1 ←
          alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice
            hashing.Hash) current i2
        let h2 ← merkle.node_hash h h1
        alloc.vec.Vec.push next h2
      else
        let h ←
          alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice
            hashing.Hash) current i
        alloc.vec.Vec.push next h
    let i4 ← i + 2#usize
    ok (cont (next1, i4))
  else ok (done next)

/-- [hush_core::merkle::{hush_core::merkle::MerkleTree}::from_leaves]: loop 2:
    Source: 'crates/libs/hush-core/src/merkle.rs', lines 86:12-94:13 -/
@[rust_loop]
def merkle.MerkleTree.from_leaves_loop1_loop0
  (current : alloc.vec.Vec hashing.Hash) (next : alloc.vec.Vec hashing.Hash)
  (i : Std.Usize) :
  Result (alloc.vec.Vec hashing.Hash)
  := do
  loop
    (fun (next1, i1) => merkle.MerkleTree.from_leaves_loop1_loop0.body current
      next1 i1)
    (next, i)

/-- [hush_core::merkle::{hush_core::merkle::MerkleTree}::from_leaves]: loop body 1:
    Source: 'crates/libs/hush-core/src/merkle.rs', lines 83:8-97:9 -/
@[rust_loop_body]
def merkle.MerkleTree.from_leaves_loop1.body
  (levels : alloc.vec.Vec (alloc.vec.Vec hashing.Hash))
  (current : alloc.vec.Vec hashing.Hash) :
  Result (ControlFlow ((alloc.vec.Vec (alloc.vec.Vec hashing.Hash)) ×
    (alloc.vec.Vec hashing.Hash)) (alloc.vec.Vec (alloc.vec.Vec hashing.Hash)))
  := do
  let i := alloc.vec.Vec.len current
  if i > 1#usize
  then
    let i1 := alloc.vec.Vec.len current
    let i2 ← core.num.Usize.div_ceil i1 2#usize
    let next := alloc.vec.Vec.with_capacity hashing.Hash i2
    let next1 ←
      merkle.MerkleTree.from_leaves_loop1_loop0 current next 0#usize
    let v ← alloc.vec.CloneVec.clone hashing.Hash.Insts.CoreCloneClone next1
    let levels1 ← alloc.vec.Vec.push levels v
    ok (cont (levels1, next1))
  else ok (done levels)

/-- [hush_core::merkle::{hush_core::merkle::MerkleTree}::from_leaves]: loop 1:
    Source: 'crates/libs/hush-core/src/merkle.rs', lines 83:8-97:9 -/
@[rust_loop]
def merkle.MerkleTree.from_leaves_loop1
  (levels : alloc.vec.Vec (alloc.vec.Vec hashing.Hash))
  (current : alloc.vec.Vec hashing.Hash) :
  Result (alloc.vec.Vec (alloc.vec.Vec hashing.Hash))
  := do
  loop
    (fun (levels1, current1) => merkle.MerkleTree.from_leaves_loop1.body
      levels1 current1)
    (levels, current)

/-- [hush_core::merkle::{hush_core::merkle::MerkleTree}::from_leaves]:
    Source: 'crates/libs/hush-core/src/merkle.rs', lines 69:4-100:5 -/
def merkle.MerkleTree.from_leaves
  {T : Type} (coreconvertAsRefTSliceU8Inst : core.convert.AsRef T (Slice
  Std.U8)) (leaves : Slice T) :
  Result (core.result.Result merkle.MerkleTree error.Error)
  := do
  let b ← core.slice.Slice.is_empty leaves
  if b
  then ok (core.result.Result.Err error.Error.EmptyTree)
  else
    let i := Slice.len leaves
    let current := alloc.vec.Vec.with_capacity hashing.Hash i
    let current1 ←
      merkle.MerkleTree.from_leaves_loop0 coreconvertAsRefTSliceU8Inst leaves
        current 0#usize
    let v ←
      alloc.vec.CloneVec.clone hashing.Hash.Insts.CoreCloneClone current1
    let levels ←
      alloc.vec.Vec.push (alloc.vec.Vec.new (alloc.vec.Vec hashing.Hash)) v
    let levels1 ← merkle.MerkleTree.from_leaves_loop1 levels current1
    ok (core.result.Result.Ok { levels := levels1 })

/-- [hush_core::merkle::{hush_core::merkle::MerkleTree}::from_hashes]: loop body 1:
    Source: 'crates/libs/hush-core/src/merkle.rs', lines 115:12-122:13 -/
@[rust_loop_body]
def merkle.MerkleTree.from_hashes_loop0_loop0.body
  (current : alloc.vec.Vec hashing.Hash) (next : alloc.vec.Vec hashing.Hash)
  (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec hashing.Hash) × Std.Usize)
    (alloc.vec.Vec hashing.Hash))
  := do
  let i1 := alloc.vec.Vec.len current
  if i < i1
  then
    let i2 ← i + 1#usize
    let i3 := alloc.vec.Vec.len current
    let next1 ←
      if i2 < i3
      then
        let h ←
          alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice
            hashing.Hash) current i
        let h1 ←
          alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice
            hashing.Hash) current i2
        let h2 ← merkle.node_hash h h1
        alloc.vec.Vec.push next h2
      else
        let h ←
          alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice
            hashing.Hash) current i
        alloc.vec.Vec.push next h
    let i4 ← i + 2#usize
    ok (cont (next1, i4))
  else ok (done next)

/-- [hush_core::merkle::{hush_core::merkle::MerkleTree}::from_hashes]: loop 1:
    Source: 'crates/libs/hush-core/src/merkle.rs', lines 115:12-122:13 -/
@[rust_loop]
def merkle.MerkleTree.from_hashes_loop0_loop0
  (current : alloc.vec.Vec hashing.Hash) (next : alloc.vec.Vec hashing.Hash)
  (i : Std.Usize) :
  Result (alloc.vec.Vec hashing.Hash)
  := do
  loop
    (fun (next1, i1) => merkle.MerkleTree.from_hashes_loop0_loop0.body current
      next1 i1)
    (next, i)

/-- [hush_core::merkle::{hush_core::merkle::MerkleTree}::from_hashes]: loop body 0:
    Source: 'crates/libs/hush-core/src/merkle.rs', lines 112:8-125:9 -/
@[rust_loop_body]
def merkle.MerkleTree.from_hashes_loop0.body
  (levels : alloc.vec.Vec (alloc.vec.Vec hashing.Hash))
  (current : alloc.vec.Vec hashing.Hash) :
  Result (ControlFlow ((alloc.vec.Vec (alloc.vec.Vec hashing.Hash)) ×
    (alloc.vec.Vec hashing.Hash)) (alloc.vec.Vec (alloc.vec.Vec hashing.Hash)))
  := do
  let i := alloc.vec.Vec.len current
  if i > 1#usize
  then
    let i1 := alloc.vec.Vec.len current
    let i2 ← core.num.Usize.div_ceil i1 2#usize
    let next := alloc.vec.Vec.with_capacity hashing.Hash i2
    let next1 ←
      merkle.MerkleTree.from_hashes_loop0_loop0 current next 0#usize
    let v ← alloc.vec.CloneVec.clone hashing.Hash.Insts.CoreCloneClone next1
    let levels1 ← alloc.vec.Vec.push levels v
    ok (cont (levels1, next1))
  else ok (done levels)

/-- [hush_core::merkle::{hush_core::merkle::MerkleTree}::from_hashes]: loop 0:
    Source: 'crates/libs/hush-core/src/merkle.rs', lines 112:8-125:9 -/
@[rust_loop]
def merkle.MerkleTree.from_hashes_loop0
  (levels : alloc.vec.Vec (alloc.vec.Vec hashing.Hash))
  (current : alloc.vec.Vec hashing.Hash) :
  Result (alloc.vec.Vec (alloc.vec.Vec hashing.Hash))
  := do
  loop
    (fun (levels1, current1) => merkle.MerkleTree.from_hashes_loop0.body
      levels1 current1)
    (levels, current)

/-- [hush_core::merkle::{hush_core::merkle::MerkleTree}::from_hashes]:
    Source: 'crates/libs/hush-core/src/merkle.rs', lines 103:4-128:5 -/
def merkle.MerkleTree.from_hashes
  (leaf_hashes : alloc.vec.Vec hashing.Hash) :
  Result (core.result.Result merkle.MerkleTree error.Error)
  := do
  let b ← alloc.vec.Vec.is_empty Global leaf_hashes
  if b
  then ok (core.result.Result.Err error.Error.EmptyTree)
  else
    let v ←
      alloc.vec.CloneVec.clone hashing.Hash.Insts.CoreCloneClone leaf_hashes
    let levels ←
      alloc.vec.Vec.push (alloc.vec.Vec.new (alloc.vec.Vec hashing.Hash)) v
    let levels1 ← merkle.MerkleTree.from_hashes_loop0 levels leaf_hashes
    ok (core.result.Result.Ok { levels := levels1 })

/-- [hush_core::merkle::{hush_core::merkle::MerkleTree}::leaf_count]:
    Source: 'crates/libs/hush-core/src/merkle.rs', lines 131:4-137:5 -/
def merkle.MerkleTree.leaf_count
  (self : merkle.MerkleTree) : Result Std.Usize := do
  let b ← alloc.vec.Vec.is_empty Global self.levels
  if b
  then ok 0#usize
  else
    let v ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice (alloc.vec.Vec
        hashing.Hash)) self.levels 0#usize
    ok (alloc.vec.Vec.len v)

/-- [hush_core::merkle::{hush_core::merkle::MerkleTree}::root]:
    Source: 'crates/libs/hush-core/src/merkle.rs', lines 140:4-151:5 -/
def merkle.MerkleTree.root
  (self : merkle.MerkleTree) : Result hashing.Hash := do
  let b ← alloc.vec.Vec.is_empty Global self.levels
  if b
  then hashing.Hash.zero
  else
    let i := alloc.vec.Vec.len self.levels
    let i1 ← i - 1#usize
    let last ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice (alloc.vec.Vec
        hashing.Hash)) self.levels i1
    let b1 ← alloc.vec.Vec.is_empty Global last
    if b1
    then hashing.Hash.zero
    else
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice hashing.Hash)
        last 0#usize

/-- [hush_core::merkle::{hush_core::merkle::MerkleTree}::inclusion_proof]: loop body 0:
    Source: 'crates/libs/hush-core/src/merkle.rs', lines 178:8-195:9 -/
@[rust_loop_body]
def merkle.MerkleTree.inclusion_proof_loop.body
  (self : merkle.MerkleTree) (audit_path : alloc.vec.Vec hashing.Hash)
  (idx : Std.Usize) (level_idx : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec hashing.Hash) × Std.Usize × Std.Usize)
    (alloc.vec.Vec hashing.Hash))
  := do
  let i := alloc.vec.Vec.len self.levels
  if level_idx < i
  then
    let v ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice (alloc.vec.Vec
        hashing.Hash)) self.levels level_idx
    let level_len := alloc.vec.Vec.len v
    if level_len <= 1#usize
    then ok (done audit_path)
    else
      let b ← core.num.Usize.is_multiple_of idx 2#usize
      let audit_path1 ←
        if b
        then
          let sib ← idx + 1#usize
          if sib < level_len
          then
            let h ←
              alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice
                hashing.Hash) v sib
            alloc.vec.Vec.push audit_path h
          else ok audit_path
        else
          let i1 ← idx - 1#usize
          let h ←
            alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice
              hashing.Hash) v i1
          alloc.vec.Vec.push audit_path h
      let idx1 ← idx / 2#usize
      let level_idx1 ← level_idx + 1#usize
      ok (cont (audit_path1, idx1, level_idx1))
  else ok (done audit_path)

/-- [hush_core::merkle::{hush_core::merkle::MerkleTree}::inclusion_proof]: loop 0:
    Source: 'crates/libs/hush-core/src/merkle.rs', lines 178:8-195:9 -/
@[rust_loop]
def merkle.MerkleTree.inclusion_proof_loop
  (self : merkle.MerkleTree) (audit_path : alloc.vec.Vec hashing.Hash)
  (idx : Std.Usize) (level_idx : Std.Usize) :
  Result (alloc.vec.Vec hashing.Hash)
  := do
  loop
    (fun (audit_path1, idx1, level_idx1) =>
      merkle.MerkleTree.inclusion_proof_loop.body self audit_path1 idx1
      level_idx1)
    (audit_path, idx, level_idx)

/-- [hush_core::merkle::{hush_core::merkle::MerkleTree}::inclusion_proof]:
    Source: 'crates/libs/hush-core/src/merkle.rs', lines 165:4-202:5 -/
def merkle.MerkleTree.inclusion_proof
  (self : merkle.MerkleTree) (leaf_index : Std.Usize) :
  Result (core.result.Result merkle.MerkleProof error.Error)
  := do
  let tree_size ← merkle.MerkleTree.leaf_count self
  if leaf_index >= tree_size
  then
    ok (core.result.Result.Err (error.Error.InvalidProofIndex leaf_index
      tree_size))
  else
    let audit_path ←
      merkle.MerkleTree.inclusion_proof_loop self (alloc.vec.Vec.new
        hashing.Hash) leaf_index 0#usize
    ok (core.result.Result.Ok { tree_size, leaf_index, audit_path })

/-- [hush_core::merkle::{core::clone::Clone for hush_core::merkle::MerkleProof}::clone]:
    Source: 'crates/libs/hush-core/src/merkle.rs', lines 206:9-206:14 -/
def merkle.MerkleProof.Insts.CoreCloneClone.clone
  (self : merkle.MerkleProof) : Result merkle.MerkleProof := do
  let i ← lift (core.clone.impls.CloneUsize.clone self.tree_size)
  let i1 ← lift (core.clone.impls.CloneUsize.clone self.leaf_index)
  let v ←
    alloc.vec.CloneVec.clone hashing.Hash.Insts.CoreCloneClone self.audit_path
  ok { tree_size := i, leaf_index := i1, audit_path := v }

/-- Trait implementation: [hush_core::merkle::{core::clone::Clone for hush_core::merkle::MerkleProof}]
    Source: 'crates/libs/hush-core/src/merkle.rs', lines 206:9-206:14 -/
@[reducible]
def merkle.MerkleProof.Insts.CoreCloneClone : core.clone.Clone
  merkle.MerkleProof := {
  clone := merkle.MerkleProof.Insts.CoreCloneClone.clone
}

/-- [hush_core::merkle::{core::fmt::Debug for hush_core::merkle::MerkleProof}::fmt]:
    Source: 'crates/libs/hush-core/src/merkle.rs', lines 206:16-206:21 -/
def merkle.MerkleProof.Insts.CoreFmtDebug.fmt
  (self : merkle.MerkleProof) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ core.fmt.DebugUsize self.tree_size
  let dyn1 := Dyn.mk _ core.fmt.DebugUsize self.leaf_index
  let dyn2 :=
    Dyn.mk _ (core.fmt.DebugShared (core.fmt.DebugVec
      hashing.Hash.Insts.CoreFmtDebug)) self.audit_path
  core.fmt.Formatter.debug_struct_field3_finish f (toStr "MerkleProof") (toStr
    "tree_size") dyn (toStr "leaf_index") dyn1 (toStr "audit_path") dyn2

/-- Trait implementation: [hush_core::merkle::{core::fmt::Debug for hush_core::merkle::MerkleProof}]
    Source: 'crates/libs/hush-core/src/merkle.rs', lines 206:16-206:21 -/
@[reducible]
def merkle.MerkleProof.Insts.CoreFmtDebug : core.fmt.Debug merkle.MerkleProof
  := {
  fmt := merkle.MerkleProof.Insts.CoreFmtDebug.fmt
}

/-- [hush_core::merkle::_::{serde_core::ser::Serialize for hush_core::merkle::MerkleProof}::serialize]:
    Source: 'crates/libs/hush-core/src/merkle.rs', lines 206:23-206:32 -/
def merkle.MerkleProof.Insts.Serde_coreSerSerialize.serialize
  {__S : Type} {Clause0_Ok : Type} {Clause0_Error : Type} {Clause0_SerializeSeq
  : Type} {Clause0_SerializeTuple : Type} {Clause0_SerializeTupleStruct : Type}
  {Clause0_SerializeTupleVariant : Type} {Clause0_SerializeMap : Type}
  {Clause0_SerializeStruct : Type} {Clause0_SerializeStructVariant : Type}
  (serde_coreserSerializerInst : serde_core.ser.Serializer __S Clause0_Ok
  Clause0_Error Clause0_SerializeSeq Clause0_SerializeTuple
  Clause0_SerializeTupleStruct Clause0_SerializeTupleVariant
  Clause0_SerializeMap Clause0_SerializeStruct Clause0_SerializeStructVariant)
  (self : merkle.MerkleProof) (__serializer : __S) :
  Result (core.result.Result Clause0_Ok Clause0_Error)
  := do
  sorry

/-- Trait implementation: [hush_core::merkle::_::{serde_core::ser::Serialize for hush_core::merkle::MerkleProof}]
    Source: 'crates/libs/hush-core/src/merkle.rs', lines 206:23-206:32 -/
@[reducible]
def merkle.MerkleProof.Insts.Serde_coreSerSerialize : serde_core.ser.Serialize
  merkle.MerkleProof := {
  serialize := fun {__S : Type} {Clause0_Ok : Type} {Clause0_Error : Type}
    {Clause0_SerializeSeq : Type} {Clause0_SerializeTuple : Type}
    {Clause0_SerializeTupleStruct : Type} {Clause0_SerializeTupleVariant :
    Type} {Clause0_SerializeMap : Type} {Clause0_SerializeStruct : Type}
    {Clause0_SerializeStructVariant : Type} (serde_coreserSerializerInst :
    serde_core.ser.Serializer __S Clause0_Ok Clause0_Error Clause0_SerializeSeq
    Clause0_SerializeTuple Clause0_SerializeTupleStruct
    Clause0_SerializeTupleVariant Clause0_SerializeMap Clause0_SerializeStruct
    Clause0_SerializeStructVariant) =>
    merkle.MerkleProof.Insts.Serde_coreSerSerialize.serialize
    serde_coreserSerializerInst
}

/-- [hush_core::merkle::_]
    Source: 'crates/libs/hush-core/src/merkle.rs', lines 206:23-206:32 -/
@[global_simps, irreducible] def merkle._ : Unit := ()

/-- [hush_core::merkle::_#1::{serde_core::de::Deserialize<'de> for hush_core::merkle::MerkleProof}::deserialize::FIELDS]
    Source: 'crates/libs/hush-core/src/merkle.rs', lines 206:34-206:45 -/
@[global_simps, irreducible]
def merkle.__1.DeserializeDeMerkleProof.deserialize.FIELDS : Slice Str :=
  Array.to_slice
    (Array.make 3#usize [
      toStr "tree_size", toStr "leaf_index", toStr "audit_path"
      ])

/-- [hush_core::merkle::_#1::{serde_core::de::Deserialize<'de> for hush_core::merkle::MerkleProof}::deserialize::{serde_core::de::Visitor<'de, hush_core::merkle::_#1::{serde_core::de::Deserialize<'de> for hush_core::merkle::MerkleProof}::deserialize::__Field> for hush_core::merkle::_#1::{serde_core::de::Deserialize<'de> for hush_core::merkle::MerkleProof}::deserialize::__FieldVisitor}::visit_bytes]:
    Source: 'crates/libs/hush-core/src/merkle.rs', lines 206:34-206:45 -/
def
  merkle.__1.DeserializeDeMerkleProof.deserialize.__FieldVisitor.Insts.Serde_coreDeVisitorDe__Field.visit_bytes
  {__E : Type} (serde_coredeErrorInst : serde_core.de.Error __E)
  (self : merkle.__1.DeserializeDeMerkleProof.deserialize.__FieldVisitor)
  (__value : Slice Std.U8) :
  Result (core.result.Result
    merkle.__1.DeserializeDeMerkleProof.deserialize.__Field __E)
  := do
  sorry

/-- [hush_core::merkle::_#1::{serde_core::de::Deserialize<'de> for hush_core::merkle::MerkleProof}::deserialize::{serde_core::de::Visitor<'de, hush_core::merkle::_#1::{serde_core::de::Deserialize<'de> for hush_core::merkle::MerkleProof}::deserialize::__Field> for hush_core::merkle::_#1::{serde_core::de::Deserialize<'de> for hush_core::merkle::MerkleProof}::deserialize::__FieldVisitor}::visit_str]:
    Source: 'crates/libs/hush-core/src/merkle.rs', lines 206:34-206:45 -/
def
  merkle.__1.DeserializeDeMerkleProof.deserialize.__FieldVisitor.Insts.Serde_coreDeVisitorDe__Field.visit_str
  {__E : Type} (serde_coredeErrorInst : serde_core.de.Error __E)
  (self : merkle.__1.DeserializeDeMerkleProof.deserialize.__FieldVisitor)
  (__value : Str) :
  Result (core.result.Result
    merkle.__1.DeserializeDeMerkleProof.deserialize.__Field __E)
  := do
  let b ← Str.Insts.CoreCmpPartialEqStr.eq __value (toStr "tree_size")
  if b
  then
    ok (core.result.Result.Ok
      merkle.__1.DeserializeDeMerkleProof.deserialize.__Field.__field0)
  else
    let b1 ← Str.Insts.CoreCmpPartialEqStr.eq __value (toStr "leaf_index")
    if b1
    then
      ok (core.result.Result.Ok
        merkle.__1.DeserializeDeMerkleProof.deserialize.__Field.__field1)
    else
      let b2 ← Str.Insts.CoreCmpPartialEqStr.eq __value (toStr "audit_path")
      if b2
      then
        ok (core.result.Result.Ok
          merkle.__1.DeserializeDeMerkleProof.deserialize.__Field.__field2)
      else
        ok (core.result.Result.Ok
          merkle.__1.DeserializeDeMerkleProof.deserialize.__Field.__ignore)

/-- [hush_core::merkle::_#1::{serde_core::de::Deserialize<'de> for hush_core::merkle::MerkleProof}::deserialize::{serde_core::de::Visitor<'de, hush_core::merkle::_#1::{serde_core::de::Deserialize<'de> for hush_core::merkle::MerkleProof}::deserialize::__Field> for hush_core::merkle::_#1::{serde_core::de::Deserialize<'de> for hush_core::merkle::MerkleProof}::deserialize::__FieldVisitor}::visit_u64]:
    Source: 'crates/libs/hush-core/src/merkle.rs', lines 206:34-206:45 -/
def
  merkle.__1.DeserializeDeMerkleProof.deserialize.__FieldVisitor.Insts.Serde_coreDeVisitorDe__Field.visit_u64
  {__E : Type} (serde_coredeErrorInst : serde_core.de.Error __E)
  (self : merkle.__1.DeserializeDeMerkleProof.deserialize.__FieldVisitor)
  (__value : Std.U64) :
  Result (core.result.Result
    merkle.__1.DeserializeDeMerkleProof.deserialize.__Field __E)
  := do
  match __value with
  | 0#uscalar =>
    ok (core.result.Result.Ok
      merkle.__1.DeserializeDeMerkleProof.deserialize.__Field.__field0)
  | 1#uscalar =>
    ok (core.result.Result.Ok
      merkle.__1.DeserializeDeMerkleProof.deserialize.__Field.__field1)
  | 2#uscalar =>
    ok (core.result.Result.Ok
      merkle.__1.DeserializeDeMerkleProof.deserialize.__Field.__field2)
  | _ =>
    ok (core.result.Result.Ok
      merkle.__1.DeserializeDeMerkleProof.deserialize.__Field.__ignore)

/-- [hush_core::merkle::_#1::{serde_core::de::Deserialize<'de> for hush_core::merkle::MerkleProof}::deserialize::{serde_core::de::Visitor<'de, hush_core::merkle::_#1::{serde_core::de::Deserialize<'de> for hush_core::merkle::MerkleProof}::deserialize::__Field> for hush_core::merkle::_#1::{serde_core::de::Deserialize<'de> for hush_core::merkle::MerkleProof}::deserialize::__FieldVisitor}::expecting]:
    Source: 'crates/libs/hush-core/src/merkle.rs', lines 206:34-206:45 -/
def
  merkle.__1.DeserializeDeMerkleProof.deserialize.__FieldVisitor.Insts.Serde_coreDeVisitorDe__Field.expecting
  (self : merkle.__1.DeserializeDeMerkleProof.deserialize.__FieldVisitor)
  (__formatter : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  core.fmt.Formatter.write_str __formatter (toStr "field identifier")

/-- Trait implementation: [hush_core::merkle::_#1::{serde_core::de::Deserialize<'de> for hush_core::merkle::MerkleProof}::deserialize::{serde_core::de::Visitor<'de, hush_core::merkle::_#1::{serde_core::de::Deserialize<'de> for hush_core::merkle::MerkleProof}::deserialize::__Field> for hush_core::merkle::_#1::{serde_core::de::Deserialize<'de> for hush_core::merkle::MerkleProof}::deserialize::__FieldVisitor}]
    Source: 'crates/libs/hush-core/src/merkle.rs', lines 206:34-206:45 -/
@[reducible]
def
  merkle.__1.DeserializeDeMerkleProof.deserialize.__FieldVisitor.Insts.Serde_coreDeVisitorDe__Field
  : serde_core.de.Visitor
  merkle.__1.DeserializeDeMerkleProof.deserialize.__FieldVisitor
  merkle.__1.DeserializeDeMerkleProof.deserialize.__Field := {
  expecting :=
    merkle.__1.DeserializeDeMerkleProof.deserialize.__FieldVisitor.Insts.Serde_coreDeVisitorDe__Field.expecting
  visit_u64 := fun {__E : Type} (serde_coredeErrorInst : serde_core.de.Error
    __E) =>
    merkle.__1.DeserializeDeMerkleProof.deserialize.__FieldVisitor.Insts.Serde_coreDeVisitorDe__Field.visit_u64
    serde_coredeErrorInst
  visit_str := fun {__E : Type} (serde_coredeErrorInst : serde_core.de.Error
    __E) =>
    merkle.__1.DeserializeDeMerkleProof.deserialize.__FieldVisitor.Insts.Serde_coreDeVisitorDe__Field.visit_str
    serde_coredeErrorInst
  visit_bytes := fun {__E : Type} (serde_coredeErrorInst : serde_core.de.Error
    __E) =>
    merkle.__1.DeserializeDeMerkleProof.deserialize.__FieldVisitor.Insts.Serde_coreDeVisitorDe__Field.visit_bytes
    serde_coredeErrorInst
  visit_seq := fun {A : Type} {Clause0_Error : Type} (serde_coredeSeqAccessInst
    : serde_core.de.SeqAccess A Clause0_Error) =>
    merkle.__1.DeserializeDeMerkleProof.deserialize.__FieldVisitor.Insts.Serde_coreDeVisitorDe__Field.visit_seq
    serde_coredeSeqAccessInst
  visit_map := fun {A : Type} {Clause0_Error : Type} (serde_coredeMapAccessInst
    : serde_core.de.MapAccess A Clause0_Error) =>
    merkle.__1.DeserializeDeMerkleProof.deserialize.__FieldVisitor.Insts.Serde_coreDeVisitorDe__Field.visit_map
    serde_coredeMapAccessInst
}

/-- [hush_core::merkle::_#1::{serde_core::de::Deserialize<'de> for hush_core::merkle::MerkleProof}::deserialize::{serde_core::de::Deserialize<'de> for hush_core::merkle::_#1::{serde_core::de::Deserialize<'de> for hush_core::merkle::MerkleProof}::deserialize::__Field}::deserialize]:
    Source: 'crates/libs/hush-core/src/merkle.rs', lines 206:34-206:45 -/
def
  merkle.__1.DeserializeDeMerkleProof.deserialize.__Field.Insts.Serde_coreDeDeserialize.deserialize
  {__D : Type} {Clause0_Error : Type} (serde_coredeDeserializerInst :
  serde_core.de.Deserializer __D Clause0_Error) (__deserializer : __D) :
  Result (core.result.Result
    merkle.__1.DeserializeDeMerkleProof.deserialize.__Field Clause0_Error)
  := do
  serde_coredeDeserializerInst.deserialize_identifier
    merkle.__1.DeserializeDeMerkleProof.deserialize.__FieldVisitor.Insts.Serde_coreDeVisitorDe__Field
    __deserializer ()

/-- Trait implementation: [hush_core::merkle::_#1::{serde_core::de::Deserialize<'de> for hush_core::merkle::MerkleProof}::deserialize::{serde_core::de::Deserialize<'de> for hush_core::merkle::_#1::{serde_core::de::Deserialize<'de> for hush_core::merkle::MerkleProof}::deserialize::__Field}]
    Source: 'crates/libs/hush-core/src/merkle.rs', lines 206:34-206:45 -/
@[reducible]
def
  merkle.__1.DeserializeDeMerkleProof.deserialize.__Field.Insts.Serde_coreDeDeserialize
  : serde_core.de.Deserialize
  merkle.__1.DeserializeDeMerkleProof.deserialize.__Field := {
  deserialize := fun {__D : Type} {Clause0_Error : Type}
    (serde_coredeDeserializerInst : serde_core.de.Deserializer __D
    Clause0_Error) =>
    merkle.__1.DeserializeDeMerkleProof.deserialize.__Field.Insts.Serde_coreDeDeserialize.deserialize
    serde_coredeDeserializerInst
}

/-- [hush_core::merkle::_#1::{serde_core::de::Deserialize<'de> for hush_core::merkle::MerkleProof}::deserialize::{serde_core::de::Visitor<'de, hush_core::merkle::MerkleProof> for hush_core::merkle::_#1::{serde_core::de::Deserialize<'de> for hush_core::merkle::MerkleProof}::deserialize::__Visitor<'de>}::visit_map]:
    Source: 'crates/libs/hush-core/src/merkle.rs', lines 206:34-206:45 -/
def
  merkle.__1.DeserializeDeMerkleProof.deserialize.__Visitor.Insts.Serde_coreDeVisitorDeMerkleProof.visit_map
  {__A : Type} {Clause0_Error : Type} (serde_coredeMapAccessInst :
  serde_core.de.MapAccess __A Clause0_Error)
  (self : merkle.__1.DeserializeDeMerkleProof.deserialize.__Visitor)
  (__map : __A) :
  Result (core.result.Result merkle.MerkleProof Clause0_Error)
  := do
  sorry

/-- [hush_core::merkle::_#1::{serde_core::de::Deserialize<'de> for hush_core::merkle::MerkleProof}::deserialize::{serde_core::de::Visitor<'de, hush_core::merkle::MerkleProof> for hush_core::merkle::_#1::{serde_core::de::Deserialize<'de> for hush_core::merkle::MerkleProof}::deserialize::__Visitor<'de>}::visit_seq]:
    Source: 'crates/libs/hush-core/src/merkle.rs', lines 206:34-206:45 -/
def
  merkle.__1.DeserializeDeMerkleProof.deserialize.__Visitor.Insts.Serde_coreDeVisitorDeMerkleProof.visit_seq
  {__A : Type} {Clause0_Error : Type} (serde_coredeSeqAccessInst :
  serde_core.de.SeqAccess __A Clause0_Error)
  (self : merkle.__1.DeserializeDeMerkleProof.deserialize.__Visitor)
  (__seq : __A) :
  Result (core.result.Result merkle.MerkleProof Clause0_Error)
  := do
  let (r, __seq1) ←
    serde_coredeSeqAccessInst.next_element Usize.Insts.Serde_coreDeDeserialize
      __seq
  let cf ←
    core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    match val with
    | none =>
      let dyn :=
        Dyn.mk _ Shared0Str.Insts.Serde_coreDeExpected (toStr
          "struct MerkleProof with 3 elements")
      let t ← serde_coredeSeqAccessInst.ErrorInst.invalid_length 0#usize dyn
      ok (core.result.Result.Err t)
    | some __value =>
      let (r1, __seq2) ←
        serde_coredeSeqAccessInst.next_element
          Usize.Insts.Serde_coreDeDeserialize __seq1
      let cf1 ←
        core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch
          r1
      match cf1 with
      | core.ops.control_flow.ControlFlow.Continue val1 =>
        match val1 with
        | none =>
          let dyn :=
            Dyn.mk _ Shared0Str.Insts.Serde_coreDeExpected (toStr
              "struct MerkleProof with 3 elements")
          let t ←
            serde_coredeSeqAccessInst.ErrorInst.invalid_length 1#usize dyn
          ok (core.result.Result.Err t)
        | some __value1 =>
          let (r2, _) ←
            serde_coredeSeqAccessInst.next_element
              (alloc.vec.Vec.Insts.Serde_coreDeDeserialize
              hashing.Hash.Insts.Serde_coreDeDeserialize) __seq2
          let cf2 ←
            core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch
              r2
          match cf2 with
          | core.ops.control_flow.ControlFlow.Continue val2 =>
            match val2 with
            | none =>
              let dyn :=
                Dyn.mk _ Shared0Str.Insts.Serde_coreDeExpected (toStr
                  "struct MerkleProof with 3 elements")
              let t ←
                serde_coredeSeqAccessInst.ErrorInst.invalid_length 2#usize dyn
              ok (core.result.Result.Err t)
            | some __value2 =>
              ok (core.result.Result.Ok
                {
                  tree_size := __value,
                  leaf_index := __value1,
                  audit_path := __value2
                })
          | core.ops.control_flow.ControlFlow.Break residual =>
            core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
              merkle.MerkleProof (core.convert.FromSame Clause0_Error) residual
      | core.ops.control_flow.ControlFlow.Break residual =>
        core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
          merkle.MerkleProof (core.convert.FromSame Clause0_Error) residual
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
      merkle.MerkleProof (core.convert.FromSame Clause0_Error) residual

/-- [hush_core::merkle::_#1::{serde_core::de::Deserialize<'de> for hush_core::merkle::MerkleProof}::deserialize::{serde_core::de::Visitor<'de, hush_core::merkle::MerkleProof> for hush_core::merkle::_#1::{serde_core::de::Deserialize<'de> for hush_core::merkle::MerkleProof}::deserialize::__Visitor<'de>}::expecting]:
    Source: 'crates/libs/hush-core/src/merkle.rs', lines 206:34-206:45 -/
def
  merkle.__1.DeserializeDeMerkleProof.deserialize.__Visitor.Insts.Serde_coreDeVisitorDeMerkleProof.expecting
  (self : merkle.__1.DeserializeDeMerkleProof.deserialize.__Visitor)
  (__formatter : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  core.fmt.Formatter.write_str __formatter (toStr "struct MerkleProof")

/-- Trait implementation: [hush_core::merkle::_#1::{serde_core::de::Deserialize<'de> for hush_core::merkle::MerkleProof}::deserialize::{serde_core::de::Visitor<'de, hush_core::merkle::MerkleProof> for hush_core::merkle::_#1::{serde_core::de::Deserialize<'de> for hush_core::merkle::MerkleProof}::deserialize::__Visitor<'de>}]
    Source: 'crates/libs/hush-core/src/merkle.rs', lines 206:34-206:45 -/
@[reducible]
def
  merkle.__1.DeserializeDeMerkleProof.deserialize.__Visitor.Insts.Serde_coreDeVisitorDeMerkleProof
  : serde_core.de.Visitor
  merkle.__1.DeserializeDeMerkleProof.deserialize.__Visitor merkle.MerkleProof
  := {
  expecting :=
    merkle.__1.DeserializeDeMerkleProof.deserialize.__Visitor.Insts.Serde_coreDeVisitorDeMerkleProof.expecting
  visit_u64 := fun {E : Type} (serde_coredeErrorInst : serde_core.de.Error E)
    =>
    merkle.__1.DeserializeDeMerkleProof.deserialize.__Visitor.Insts.Serde_coreDeVisitorDeMerkleProof.visit_u64
    serde_coredeErrorInst
  visit_str := fun {E : Type} (serde_coredeErrorInst : serde_core.de.Error E)
    =>
    merkle.__1.DeserializeDeMerkleProof.deserialize.__Visitor.Insts.Serde_coreDeVisitorDeMerkleProof.visit_str
    serde_coredeErrorInst
  visit_bytes := fun {E : Type} (serde_coredeErrorInst : serde_core.de.Error E)
    =>
    merkle.__1.DeserializeDeMerkleProof.deserialize.__Visitor.Insts.Serde_coreDeVisitorDeMerkleProof.visit_bytes
    serde_coredeErrorInst
  visit_seq := fun {__A : Type} {Clause0_Error : Type}
    (serde_coredeSeqAccessInst : serde_core.de.SeqAccess __A Clause0_Error) =>
    merkle.__1.DeserializeDeMerkleProof.deserialize.__Visitor.Insts.Serde_coreDeVisitorDeMerkleProof.visit_seq
    serde_coredeSeqAccessInst
  visit_map := fun {__A : Type} {Clause0_Error : Type}
    (serde_coredeMapAccessInst : serde_core.de.MapAccess __A Clause0_Error) =>
    merkle.__1.DeserializeDeMerkleProof.deserialize.__Visitor.Insts.Serde_coreDeVisitorDeMerkleProof.visit_map
    serde_coredeMapAccessInst
}

/-- [hush_core::merkle::_#1::{serde_core::de::Deserialize<'de> for hush_core::merkle::MerkleProof}::deserialize]:
    Source: 'crates/libs/hush-core/src/merkle.rs', lines 206:34-206:45 -/
def merkle.MerkleProof.Insts.Serde_coreDeDeserialize.deserialize
  {__D : Type} {Clause0_Error : Type} (serde_coredeDeserializerInst :
  serde_core.de.Deserializer __D Clause0_Error) (__deserializer : __D) :
  Result (core.result.Result merkle.MerkleProof Clause0_Error)
  := do
  sorry

/-- Trait implementation: [hush_core::merkle::_#1::{serde_core::de::Deserialize<'de> for hush_core::merkle::MerkleProof}]
    Source: 'crates/libs/hush-core/src/merkle.rs', lines 206:34-206:45 -/
@[reducible]
def merkle.MerkleProof.Insts.Serde_coreDeDeserialize :
  serde_core.de.Deserialize merkle.MerkleProof := {
  deserialize := fun {__D : Type} {Clause0_Error : Type}
    (serde_coredeDeserializerInst : serde_core.de.Deserializer __D
    Clause0_Error) =>
    merkle.MerkleProof.Insts.Serde_coreDeDeserialize.deserialize
    serde_coredeDeserializerInst
}

/-- [hush_core::merkle::_#1]
    Source: 'crates/libs/hush-core/src/merkle.rs', lines 206:34-206:45 -/
@[global_simps, irreducible] def merkle.__1 : Unit := ()

/-- [hush_core::merkle::{hush_core::merkle::MerkleProof}::compute_root_from_hash]: loop body 0:
    Source: 'crates/libs/hush-core/src/merkle.rs', lines 233:8-261:5 -/
@[rust_loop_body]
def merkle.MerkleProof.compute_root_from_hash_loop.body
  (v : alloc.vec.Vec hashing.Hash) (h : hashing.Hash) (idx : Std.Usize)
  (size : Std.Usize) (path_idx : Std.Usize) :
  Result (ControlFlow (hashing.Hash × Std.Usize × Std.Usize × Std.Usize)
    (core.result.Result hashing.Hash error.Error))
  := do
  if size > 1#usize
  then
    let b ← core.num.Usize.is_multiple_of idx 2#usize
    if b
    then
      let i ← idx + 1#usize
      if i < size
      then
        let i1 := alloc.vec.Vec.len v
        if path_idx >= i1
        then ok (done (core.result.Result.Err error.Error.MerkleProofFailed))
        else
          let sibling ←
            alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice
              hashing.Hash) v path_idx
          let path_idx1 ← path_idx + 1#usize
          let h1 ← merkle.node_hash h sibling
          let idx1 ← idx / 2#usize
          let size1 ← core.num.Usize.div_ceil size 2#usize
          ok (cont (h1, idx1, size1, path_idx1))
      else
        let idx1 ← idx / 2#usize
        let size1 ← core.num.Usize.div_ceil size 2#usize
        ok (cont (h, idx1, size1, path_idx))
    else
      let i := alloc.vec.Vec.len v
      if path_idx >= i
      then ok (done (core.result.Result.Err error.Error.MerkleProofFailed))
      else
        let sibling ←
          alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice
            hashing.Hash) v path_idx
        let path_idx1 ← path_idx + 1#usize
        let h1 ← merkle.node_hash sibling h
        let idx1 ← idx / 2#usize
        let size1 ← core.num.Usize.div_ceil size 2#usize
        ok (cont (h1, idx1, size1, path_idx1))
  else
    let i := alloc.vec.Vec.len v
    if path_idx != i
    then ok (done (core.result.Result.Err error.Error.MerkleProofFailed))
    else ok (done (core.result.Result.Ok h))

/-- [hush_core::merkle::{hush_core::merkle::MerkleProof}::compute_root_from_hash]: loop 0:
    Source: 'crates/libs/hush-core/src/merkle.rs', lines 233:8-261:5 -/
@[rust_loop]
def merkle.MerkleProof.compute_root_from_hash_loop
  (v : alloc.vec.Vec hashing.Hash) (h : hashing.Hash) (idx : Std.Usize)
  (size : Std.Usize) (path_idx : Std.Usize) :
  Result (core.result.Result hashing.Hash error.Error)
  := do
  loop
    (fun (h1, idx1, size1, path_idx1) =>
      merkle.MerkleProof.compute_root_from_hash_loop.body v h1 idx1 size1
      path_idx1)
    (h, idx, size, path_idx)

/-- [hush_core::merkle::{hush_core::merkle::MerkleProof}::compute_root_from_hash]:
    Source: 'crates/libs/hush-core/src/merkle.rs', lines 223:4-261:5 -/
def merkle.MerkleProof.compute_root_from_hash
  (self : merkle.MerkleProof) (leaf_hash : hashing.Hash) :
  Result (core.result.Result hashing.Hash error.Error)
  := do
  if self.tree_size = 0#usize
  then ok (core.result.Result.Err error.Error.MerkleProofFailed)
  else
    if self.leaf_index >= self.tree_size
    then ok (core.result.Result.Err error.Error.MerkleProofFailed)
    else
      merkle.MerkleProof.compute_root_from_hash_loop self.audit_path leaf_hash
        self.leaf_index self.tree_size 0#usize

/-- [hush_core::merkle::{hush_core::merkle::MerkleProof}::compute_root]:
    Source: 'crates/libs/hush-core/src/merkle.rs', lines 218:4-220:5 -/
def merkle.MerkleProof.compute_root
  (self : merkle.MerkleProof) (leaf_bytes : Slice Std.U8) :
  Result (core.result.Result hashing.Hash error.Error)
  := do
  let h ← merkle.leaf_hash leaf_bytes
  merkle.MerkleProof.compute_root_from_hash self h

/-- [hush_core::merkle::{hush_core::merkle::MerkleProof}::verify]:
    Source: 'crates/libs/hush-core/src/merkle.rs', lines 264:4-269:5 -/
def merkle.MerkleProof.verify
  (self : merkle.MerkleProof) (leaf_bytes : Slice Std.U8)
  (expected_root : hashing.Hash) :
  Result Bool
  := do
  let r ← merkle.MerkleProof.compute_root self leaf_bytes
  match r with
  | core.result.Result.Ok root =>
    hashing.Hash.Insts.CoreCmpPartialEqHash.eq root expected_root
  | core.result.Result.Err _ => ok false

/-- [hush_core::merkle::{hush_core::merkle::MerkleProof}::verify_hash]:
    Source: 'crates/libs/hush-core/src/merkle.rs', lines 272:4-277:5 -/
def merkle.MerkleProof.verify_hash
  (self : merkle.MerkleProof) (leaf_hash : hashing.Hash)
  (expected_root : hashing.Hash) :
  Result Bool
  := do
  let r ← merkle.MerkleProof.compute_root_from_hash self leaf_hash
  match r with
  | core.result.Result.Ok root =>
    hashing.Hash.Insts.CoreCmpPartialEqHash.eq root expected_root
  | core.result.Result.Err _ => ok false

end hush_core
