-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [hush_core]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes.
import Aeneas
import HushCore.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000
open hush_core

/-- [core::fmt::{core::fmt::Formatter<'a>}::debug_struct_field3_finish]:
    Source: '/rustc/library/core/src/fmt/mod.rs', lines 2485:4-2494:15
    Name pattern: [core::fmt::{core::fmt::Formatter<'a>}::debug_struct_field3_finish] -/
@[rust_fun "core::fmt::{core::fmt::Formatter<'a>}::debug_struct_field3_finish"]
axiom core.fmt.Formatter.debug_struct_field3_finish
  :
  core.fmt.Formatter → Str → Str → Dyn (fun _dyn => core.fmt.Debug _dyn)
    → Str → Dyn (fun _dyn => core.fmt.Debug _dyn) → Str → Dyn (fun _dyn
    => core.fmt.Debug _dyn) → Result ((core.result.Result Unit
    core.fmt.Error) × core.fmt.Formatter)

/-- [core::num::{usize}::div_ceil]:
    Source: '/rustc/library/core/src/num/uint_macros.rs', lines 3597:8-3597:54
    Name pattern: [core::num::{usize}::div_ceil] -/
@[rust_fun "core::num::{usize}::div_ceil"]
axiom core.num.Usize.div_ceil : Std.Usize → Std.Usize → Result Std.Usize

/-- [core::num::{usize}::is_multiple_of]:
    Source: '/rustc/library/core/src/num/uint_macros.rs', lines 3682:8-3682:60
    Name pattern: [core::num::{usize}::is_multiple_of] -/
@[rust_fun "core::num::{usize}::is_multiple_of"]
axiom core.num.Usize.is_multiple_of : Std.Usize → Std.Usize → Result Bool

/-- [core::option::{core::option::Option<T>}::is_some]:
    Source: '/rustc/library/core/src/option.rs', lines 635:4-635:39
    Name pattern: [core::option::{core::option::Option<@T>}::is_some] -/
@[rust_fun "core::option::{core::option::Option<@T>}::is_some"]
axiom core.option.Option.is_some {T : Type} : Option T → Result Bool

/-- [core::result::{core::ops::try_trait::Try<T, core::result::Result<core::convert::Infallible, E>> for core::result::Result<T, E>}::branch]:
    Source: '/rustc/library/core/src/result.rs', lines 2172:4-2172:64
    Name pattern: [core::result::{core::ops::try_trait::Try<core::result::Result<@T, @E>, @T, core::result::Result<core::convert::Infallible, @E>>}::branch] -/
@[rust_fun
  "core::result::{core::ops::try_trait::Try<core::result::Result<@T, @E>, @T, core::result::Result<core::convert::Infallible, @E>>}::branch"]
axiom core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch
  {T : Type} {E : Type} :
  core.result.Result T E → Result (core.ops.control_flow.ControlFlow
    (core.result.Result core.convert.Infallible E) T)

/-- [core::result::{core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible, E>> for core::result::Result<T, F>}::from_residual]:
    Source: '/rustc/library/core/src/result.rs', lines 2187:4-2187:70
    Name pattern: [core::result::{core::ops::try_trait::FromResidual<core::result::Result<@T, @F>, core::result::Result<core::convert::Infallible, @E>>}::from_residual] -/
@[rust_fun
  "core::result::{core::ops::try_trait::FromResidual<core::result::Result<@T, @F>, core::result::Result<core::convert::Infallible, @E>>}::from_residual"]
axiom
  core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
  (T : Type) {E : Type} {F : Type} (convertFromInst : core.convert.From F E) :
  core.result.Result core.convert.Infallible E → Result (core.result.Result T
    F)

/-- [core::str::traits::{core::cmp::PartialEq<str> for str}::eq]:
    Source: '/rustc/library/core/src/str/traits.rs', lines 29:4-29:37
    Name pattern: [core::str::traits::{core::cmp::PartialEq<str, str>}::eq] -/
@[rust_fun "core::str::traits::{core::cmp::PartialEq<str, str>}::eq"]
axiom Str.Insts.CoreCmpPartialEqStr.eq : Str → Str → Result Bool

/-- [alloc::vec::{alloc::vec::Vec<T>}::is_empty]:
    Source: '/rustc/library/alloc/src/vec/mod.rs', lines 2956:4-2956:40
    Name pattern: [alloc::vec::{alloc::vec::Vec<@T>}::is_empty] -/
@[rust_fun "alloc::vec::{alloc::vec::Vec<@T>}::is_empty"]
axiom alloc.vec.Vec.is_empty
  {T : Type} (A : Type) : alloc.vec.Vec T → Result Bool

/-- [serde::private::de::missing_field]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/serde-1.0.228/src/private/de.rs', lines 24:0-27:13
    Name pattern: [serde::private::de::missing_field] -/
@[rust_fun "serde::private::de::missing_field"]
axiom serde.private.de.missing_field
  {V : Type} {E : Type} (serde_coredeDeserializeInst :
  serde_core.de.Deserialize V) (serde_coredeErrorInst : serde_core.de.Error E)
  :
  Str → Result (core.result.Result V E)

/-- [serde_core::de::ignored_any::{serde_core::de::Deserialize<'de> for serde_core::de::ignored_any::IgnoredAny}::deserialize]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/serde_core-1.0.228/src/de/ignored_any.rs', lines 232:4-234:29
    Name pattern: [serde_core::de::ignored_any::{serde_core::de::Deserialize<'de, serde_core::de::ignored_any::IgnoredAny>}::deserialize] -/
@[rust_fun
  "serde_core::de::ignored_any::{serde_core::de::Deserialize<'de, serde_core::de::ignored_any::IgnoredAny>}::deserialize"]
axiom
  serde_core.de.ignored_any.IgnoredAny.Insts.Serde_coreDeDeserialize.deserialize
  {D : Type} {Clause0_Error : Type} (DeserializerInst :
  serde_core.de.Deserializer D Clause0_Error) :
  D → Result (core.result.Result serde_core.de.ignored_any.IgnoredAny
    Clause0_Error)

/-- [serde_core::de::impls::{serde_core::de::Deserialize<'de> for usize}::deserialize]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/serde_core-1.0.228/src/de/impls.rs', lines 132:12-134:37
    Name pattern: [serde_core::de::impls::{serde_core::de::Deserialize<'de, usize>}::deserialize] -/
@[rust_fun
  "serde_core::de::impls::{serde_core::de::Deserialize<'de, usize>}::deserialize"]
axiom Usize.Insts.Serde_coreDeDeserialize.deserialize
  {D : Type} {Clause0_Error : Type} (DeserializerInst :
  serde_core.de.Deserializer D Clause0_Error) :
  D → Result (core.result.Result Std.Usize Clause0_Error)

/-- [serde_core::de::impls::{serde_core::de::Deserialize<'de> for alloc::vec::Vec<T>}::deserialize]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/serde_core-1.0.228/src/de/impls.rs', lines 1139:4-1141:29
    Name pattern: [serde_core::de::impls::{serde_core::de::Deserialize<'de, alloc::vec::Vec<@T>>}::deserialize] -/
@[rust_fun
  "serde_core::de::impls::{serde_core::de::Deserialize<'de, alloc::vec::Vec<@T>>}::deserialize"]
axiom alloc.vec.Vec.Insts.Serde_coreDeDeserialize.deserialize
  {T : Type} {D : Type} {Clause1_Error : Type} (DeserializeInst :
  serde_core.de.Deserialize T) (DeserializerInst : serde_core.de.Deserializer D
  Clause1_Error) :
  D → Result (core.result.Result (alloc.vec.Vec T) Clause1_Error)

/-- [serde_core::de::Error::invalid_length]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/serde_core-1.0.228/src/de/mod.rs', lines 245:12-245:69
    Name pattern: [serde_core::de::Error::invalid_length] -/
@[rust_fun "serde_core::de::Error::invalid_length"]
axiom serde_core.de.Error.invalid_length.default
  {Self : Type} (ErrorInst : serde_core.de.Error Self) :
  Std.Usize → Dyn (fun _dyn => serde_core.de.Expected _dyn) → Result Self

/-- [serde_core::de::Error::duplicate_field]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/serde_core-1.0.228/src/de/mod.rs', lines 296:12-296:59
    Name pattern: [serde_core::de::Error::duplicate_field] -/
@[rust_fun "serde_core::de::Error::duplicate_field"]
axiom serde_core.de.Error.duplicate_field.default
  {Self : Type} (ErrorInst : serde_core.de.Error Self) : Str → Result Self

/-- [serde_core::de::{serde_core::de::Expected for &0 (str)}::fmt]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/serde_core-1.0.228/src/de/mod.rs', lines 500:4-500:64
    Name pattern: [serde_core::de::{serde_core::de::Expected<&'0 str>}::fmt] -/
@[rust_fun "serde_core::de::{serde_core::de::Expected<&'0 str>}::fmt"]
axiom Shared0Str.Insts.Serde_coreDeExpected.fmt
  :
  Str → core.fmt.Formatter → Result ((core.result.Result Unit
    core.fmt.Error) × core.fmt.Formatter)

/-- [serde_core::de::Visitor::visit_u64]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/serde_core-1.0.228/src/de/mod.rs', lines 1456:4-1458:17
    Name pattern: [serde_core::de::Visitor::visit_u64] -/
@[rust_fun "serde_core::de::Visitor::visit_u64"]
axiom serde_core.de.Visitor.visit_u64.default
  {Self : Type} {E : Type} {Clause0_Value : Type} (VisitorInst :
  serde_core.de.Visitor Self Clause0_Value) (ErrorInst : serde_core.de.Error E)
  :
  Self → Std.U64 → Result (core.result.Result Clause0_Value E)

/-- [serde_core::de::Visitor::visit_str]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/serde_core-1.0.228/src/de/mod.rs', lines 1526:4-1528:17
    Name pattern: [serde_core::de::Visitor::visit_str] -/
@[rust_fun "serde_core::de::Visitor::visit_str"]
axiom serde_core.de.Visitor.visit_str.default
  {Self : Type} {E : Type} {Clause0_Value : Type} (VisitorInst :
  serde_core.de.Visitor Self Clause0_Value) (ErrorInst : serde_core.de.Error E)
  :
  Self → Str → Result (core.result.Result Clause0_Value E)

/-- [serde_core::de::Visitor::visit_bytes]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/serde_core-1.0.228/src/de/mod.rs', lines 1586:4-1588:17
    Name pattern: [serde_core::de::Visitor::visit_bytes] -/
@[rust_fun "serde_core::de::Visitor::visit_bytes"]
axiom serde_core.de.Visitor.visit_bytes.default
  {Self : Type} {E : Type} {Clause0_Value : Type} (VisitorInst :
  serde_core.de.Visitor Self Clause0_Value) (ErrorInst : serde_core.de.Error E)
  :
  Self → Slice Std.U8 → Result (core.result.Result Clause0_Value E)

/-- [serde_core::de::Visitor::visit_seq]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/serde_core-1.0.228/src/de/mod.rs', lines 1682:4-1684:26
    Name pattern: [serde_core::de::Visitor::visit_seq] -/
@[rust_fun "serde_core::de::Visitor::visit_seq"]
axiom serde_core.de.Visitor.visit_seq.default
  {Self : Type} {A : Type} {Clause0_Value : Type} {Clause1_Error : Type}
  (VisitorInst : serde_core.de.Visitor Self Clause0_Value) (SeqAccessInst :
  serde_core.de.SeqAccess A Clause1_Error) :
  Self → A → Result (core.result.Result Clause0_Value Clause1_Error)

/-- [serde_core::de::Visitor::visit_map]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/serde_core-1.0.228/src/de/mod.rs', lines 1693:4-1695:26
    Name pattern: [serde_core::de::Visitor::visit_map] -/
@[rust_fun "serde_core::de::Visitor::visit_map"]
axiom serde_core.de.Visitor.visit_map.default
  {Self : Type} {A : Type} {Clause0_Value : Type} {Clause1_Error : Type}
  (VisitorInst : serde_core.de.Visitor Self Clause0_Value) (MapAccessInst :
  serde_core.de.MapAccess A Clause1_Error) :
  Self → A → Result (core.result.Result Clause0_Value Clause1_Error)

/-- [serde_core::de::SeqAccess::next_element]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/serde_core-1.0.228/src/de/mod.rs', lines 1769:4-1771:28
    Name pattern: [serde_core::de::SeqAccess::next_element] -/
@[rust_fun "serde_core::de::SeqAccess::next_element"]
axiom serde_core.de.SeqAccess.next_element.default
  {Self : Type} {T : Type} {Clause0_Error : Type} (SeqAccessInst :
  serde_core.de.SeqAccess Self Clause0_Error) (DeserializeInst :
  serde_core.de.Deserialize T) :
  Self → Result ((core.result.Result (Option T) Clause0_Error) × Self)

/-- [serde_core::de::MapAccess::next_key]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/serde_core-1.0.228/src/de/mod.rs', lines 1897:4-1899:28
    Name pattern: [serde_core::de::MapAccess::next_key] -/
@[rust_fun "serde_core::de::MapAccess::next_key"]
axiom serde_core.de.MapAccess.next_key.default
  {Self : Type} {K : Type} {Clause0_Error : Type} (MapAccessInst :
  serde_core.de.MapAccess Self Clause0_Error) (DeserializeInst :
  serde_core.de.Deserialize K) :
  Self → Result ((core.result.Result (Option K) Clause0_Error) × Self)

/-- [serde_core::de::MapAccess::next_value]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/serde_core-1.0.228/src/de/mod.rs', lines 1914:4-1916:28
    Name pattern: [serde_core::de::MapAccess::next_value] -/
@[rust_fun "serde_core::de::MapAccess::next_value"]
axiom serde_core.de.MapAccess.next_value.default
  {Self : Type} {V : Type} {Clause0_Error : Type} (MapAccessInst :
  serde_core.de.MapAccess Self Clause0_Error) (DeserializeInst :
  serde_core.de.Deserialize V) :
  Self → Result ((core.result.Result V Clause0_Error) × Self)

/-- [serde_core::ser::impls::{serde_core::ser::Serialize for usize}::serialize]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/serde_core-1.0.228/src/ser/impls.rs', lines 11:12-13:30
    Name pattern: [serde_core::ser::impls::{serde_core::ser::Serialize<usize>}::serialize] -/
@[rust_fun
  "serde_core::ser::impls::{serde_core::ser::Serialize<usize>}::serialize"]
axiom Usize.Insts.Serde_coreSerSerialize.serialize
  {S : Type} {Clause0_Ok : Type} {Clause0_Error : Type} {Clause0_SerializeSeq :
  Type} {Clause0_SerializeTuple : Type} {Clause0_SerializeTupleStruct : Type}
  {Clause0_SerializeTupleVariant : Type} {Clause0_SerializeMap : Type}
  {Clause0_SerializeStruct : Type} {Clause0_SerializeStructVariant : Type}
  (SerializerInst : serde_core.ser.Serializer S Clause0_Ok Clause0_Error
  Clause0_SerializeSeq Clause0_SerializeTuple Clause0_SerializeTupleStruct
  Clause0_SerializeTupleVariant Clause0_SerializeMap Clause0_SerializeStruct
  Clause0_SerializeStructVariant) :
  Std.Usize → S → Result (core.result.Result Clause0_Ok Clause0_Error)

/-- [serde_core::ser::impls::{serde_core::ser::Serialize for alloc::vec::Vec<T>}::serialize]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/serde_core-1.0.228/src/ser/impls.rs', lines 199:12-201:30
    Name pattern: [serde_core::ser::impls::{serde_core::ser::Serialize<alloc::vec::Vec<@T>>}::serialize] -/
@[rust_fun
  "serde_core::ser::impls::{serde_core::ser::Serialize<alloc::vec::Vec<@T>>}::serialize"]
axiom alloc.vec.Vec.Insts.Serde_coreSerSerialize.serialize
  {T : Type} {S : Type} {Clause1_Ok : Type} {Clause1_Error : Type}
  {Clause1_SerializeSeq : Type} {Clause1_SerializeTuple : Type}
  {Clause1_SerializeTupleStruct : Type} {Clause1_SerializeTupleVariant : Type}
  {Clause1_SerializeMap : Type} {Clause1_SerializeStruct : Type}
  {Clause1_SerializeStructVariant : Type} (SerializeInst :
  serde_core.ser.Serialize T) (SerializerInst : serde_core.ser.Serializer S
  Clause1_Ok Clause1_Error Clause1_SerializeSeq Clause1_SerializeTuple
  Clause1_SerializeTupleStruct Clause1_SerializeTupleVariant
  Clause1_SerializeMap Clause1_SerializeStruct Clause1_SerializeStructVariant)
  :
  alloc.vec.Vec T → S → Result (core.result.Result Clause1_Ok
    Clause1_Error)

/-- [hush_core::hashing::{core::clone::Clone for hush_core::hashing::Hash}::clone]:
    Source: 'crates/libs/hush-core/src/hashing.rs', lines 10:9-10:14 -/
axiom hashing.Hash.Insts.CoreCloneClone.clone
  : hashing.Hash → Result hashing.Hash

/-- [hush_core::hashing::{core::fmt::Debug for hush_core::hashing::Hash}::fmt]:
    Source: 'crates/libs/hush-core/src/hashing.rs', lines 10:22-10:27 -/
axiom hashing.Hash.Insts.CoreFmtDebug.fmt
  :
  hashing.Hash → core.fmt.Formatter → Result ((core.result.Result Unit
    core.fmt.Error) × core.fmt.Formatter)

/-- [hush_core::hashing::{core::cmp::PartialEq<hush_core::hashing::Hash> for hush_core::hashing::Hash}::eq]:
    Source: 'crates/libs/hush-core/src/hashing.rs', lines 10:29-10:38 -/
axiom hashing.Hash.Insts.CoreCmpPartialEqHash.eq
  : hashing.Hash → hashing.Hash → Result Bool

/-- [hush_core::hashing::_::{serde_core::ser::Serialize for hush_core::hashing::Hash}::serialize]:
    Source: 'crates/libs/hush-core/src/hashing.rs', lines 10:50-10:59 -/
axiom hashing.Hash.Insts.Serde_coreSerSerialize.serialize
  {__S : Type} {Clause0_Ok : Type} {Clause0_Error : Type} {Clause0_SerializeSeq
  : Type} {Clause0_SerializeTuple : Type} {Clause0_SerializeTupleStruct : Type}
  {Clause0_SerializeTupleVariant : Type} {Clause0_SerializeMap : Type}
  {Clause0_SerializeStruct : Type} {Clause0_SerializeStructVariant : Type}
  (serde_coreserSerializerInst : serde_core.ser.Serializer __S Clause0_Ok
  Clause0_Error Clause0_SerializeSeq Clause0_SerializeTuple
  Clause0_SerializeTupleStruct Clause0_SerializeTupleVariant
  Clause0_SerializeMap Clause0_SerializeStruct Clause0_SerializeStructVariant)
  :
  hashing.Hash → __S → Result (core.result.Result Clause0_Ok Clause0_Error)

/-- [hush_core::hashing::_#1::{serde_core::de::Deserialize<'de> for hush_core::hashing::Hash}::deserialize]:
    Source: 'crates/libs/hush-core/src/hashing.rs', lines 10:61-10:72 -/
axiom hashing.Hash.Insts.Serde_coreDeDeserialize.deserialize
  {__D : Type} {Clause0_Error : Type} (serde_coredeDeserializerInst :
  serde_core.de.Deserializer __D Clause0_Error) :
  __D → Result (core.result.Result hashing.Hash Clause0_Error)

/-- [hush_core::hashing::{hush_core::hashing::Hash}::zero]:
    Source: 'crates/libs/hush-core/src/hashing.rs', lines 80:4-82:5 -/
axiom hashing.Hash.zero : Result hashing.Hash

/-- [hush_core::merkle::leaf_hash]:
    Source: 'crates/libs/hush-core/src/merkle.rs', lines 27:0-36:1 -/
axiom merkle.leaf_hash : Slice Std.U8 → Result hashing.Hash

/-- [hush_core::merkle::node_hash]:
    Source: 'crates/libs/hush-core/src/merkle.rs', lines 39:0-49:1 -/
axiom merkle.node_hash : hashing.Hash → hashing.Hash → Result hashing.Hash

/-- [hush_core::merkle::_#1::{serde_core::de::Deserialize<'de> for hush_core::merkle::MerkleProof}::deserialize::{serde_core::de::Visitor<'de, hush_core::merkle::_#1::{serde_core::de::Deserialize<'de> for hush_core::merkle::MerkleProof}::deserialize::__Field> for hush_core::merkle::_#1::{serde_core::de::Deserialize<'de> for hush_core::merkle::MerkleProof}::deserialize::__FieldVisitor}::visit_map]:
    Source: 'crates/libs/hush-core/src/merkle.rs', lines 206:34-206:45 -/
axiom
  merkle.__1.DeserializeDeMerkleProof.deserialize.__FieldVisitor.Insts.Serde_coreDeVisitorDe__Field.visit_map
  {A : Type} {Clause0_Error : Type} (serde_coredeMapAccessInst :
  serde_core.de.MapAccess A Clause0_Error) :
  merkle.__1.DeserializeDeMerkleProof.deserialize.__FieldVisitor → A →
    Result (core.result.Result
    merkle.__1.DeserializeDeMerkleProof.deserialize.__Field Clause0_Error)

/-- [hush_core::merkle::_#1::{serde_core::de::Deserialize<'de> for hush_core::merkle::MerkleProof}::deserialize::{serde_core::de::Visitor<'de, hush_core::merkle::_#1::{serde_core::de::Deserialize<'de> for hush_core::merkle::MerkleProof}::deserialize::__Field> for hush_core::merkle::_#1::{serde_core::de::Deserialize<'de> for hush_core::merkle::MerkleProof}::deserialize::__FieldVisitor}::visit_seq]:
    Source: 'crates/libs/hush-core/src/merkle.rs', lines 206:34-206:45 -/
axiom
  merkle.__1.DeserializeDeMerkleProof.deserialize.__FieldVisitor.Insts.Serde_coreDeVisitorDe__Field.visit_seq
  {A : Type} {Clause0_Error : Type} (serde_coredeSeqAccessInst :
  serde_core.de.SeqAccess A Clause0_Error) :
  merkle.__1.DeserializeDeMerkleProof.deserialize.__FieldVisitor → A →
    Result (core.result.Result
    merkle.__1.DeserializeDeMerkleProof.deserialize.__Field Clause0_Error)

/-- [hush_core::merkle::_#1::{serde_core::de::Deserialize<'de> for hush_core::merkle::MerkleProof}::deserialize::{serde_core::de::Visitor<'de, hush_core::merkle::MerkleProof> for hush_core::merkle::_#1::{serde_core::de::Deserialize<'de> for hush_core::merkle::MerkleProof}::deserialize::__Visitor<'de>}::visit_bytes]:
    Source: 'crates/libs/hush-core/src/merkle.rs', lines 206:34-206:45 -/
axiom
  merkle.__1.DeserializeDeMerkleProof.deserialize.__Visitor.Insts.Serde_coreDeVisitorDeMerkleProof.visit_bytes
  {E : Type} (serde_coredeErrorInst : serde_core.de.Error E) :
  merkle.__1.DeserializeDeMerkleProof.deserialize.__Visitor → Slice Std.U8
    → Result (core.result.Result merkle.MerkleProof E)

/-- [hush_core::merkle::_#1::{serde_core::de::Deserialize<'de> for hush_core::merkle::MerkleProof}::deserialize::{serde_core::de::Visitor<'de, hush_core::merkle::MerkleProof> for hush_core::merkle::_#1::{serde_core::de::Deserialize<'de> for hush_core::merkle::MerkleProof}::deserialize::__Visitor<'de>}::visit_str]:
    Source: 'crates/libs/hush-core/src/merkle.rs', lines 206:34-206:45 -/
axiom
  merkle.__1.DeserializeDeMerkleProof.deserialize.__Visitor.Insts.Serde_coreDeVisitorDeMerkleProof.visit_str
  {E : Type} (serde_coredeErrorInst : serde_core.de.Error E) :
  merkle.__1.DeserializeDeMerkleProof.deserialize.__Visitor → Str → Result
    (core.result.Result merkle.MerkleProof E)

/-- [hush_core::merkle::_#1::{serde_core::de::Deserialize<'de> for hush_core::merkle::MerkleProof}::deserialize::{serde_core::de::Visitor<'de, hush_core::merkle::MerkleProof> for hush_core::merkle::_#1::{serde_core::de::Deserialize<'de> for hush_core::merkle::MerkleProof}::deserialize::__Visitor<'de>}::visit_u64]:
    Source: 'crates/libs/hush-core/src/merkle.rs', lines 206:34-206:45 -/
axiom
  merkle.__1.DeserializeDeMerkleProof.deserialize.__Visitor.Insts.Serde_coreDeVisitorDeMerkleProof.visit_u64
  {E : Type} (serde_coredeErrorInst : serde_core.de.Error E) :
  merkle.__1.DeserializeDeMerkleProof.deserialize.__Visitor → Std.U64 →
    Result (core.result.Result merkle.MerkleProof E)

