-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [hush_core]: external types.
-- This is a template file: rename it to "TypesExternal.lean" and fill the holes.
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/-- [hush_core::hashing::Hash]
    Source: 'crates/libs/hush-core/src/hashing.rs', lines 12:0-15:1 -/
axiom hashing.Hash : Type

