-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [hush_core]: type definitions
import Aeneas
import HushCore.TypesExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

namespace hush_core

/-- Trait declaration: [core::convert::AsRef]
    Source: '/rustc/library/core/src/convert/mod.rs', lines 220:0-220:52
    Name pattern: [core::convert::AsRef] -/
@[rust_trait "core::convert::AsRef"]
structure core.convert.AsRef (Self : Type) (T : Type) where
  as_ref : Self → Result T

/-- [core::marker::PhantomData]
    Source: '/rustc/library/core/src/marker.rs', lines 814:0-814:39
    Name pattern: [core::marker::PhantomData] -/
@[reducible, rust_type "core::marker::PhantomData"]
def core.marker.PhantomData (T : Type) := Unit

/-- Trait declaration: [serde_core::de::Expected]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/serde_core-1.0.228/src/de/mod.rs', lines 484:0-484:18
    Name pattern: [serde_core::de::Expected] -/
@[rust_trait "serde_core::de::Expected"]
structure serde_core.de.Expected (Self : Type) where
  fmt : Self → core.fmt.Formatter → Result ((core.result.Result Unit
    core.fmt.Error) × core.fmt.Formatter)

/-- Trait declaration: [serde_core::de::Error]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/serde_core-1.0.228/src/de/mod.rs', lines 165:8-165:48
    Name pattern: [serde_core::de::Error] -/
@[rust_trait "serde_core::de::Error" (parentClauses := ["coreerrorErrorInst"])]
structure serde_core.de.Error (Self : Type) where
  coreerrorErrorInst : core.error.Error Self
  custom : forall {T : Type} (corefmtDisplayInst : core.fmt.Display T), T →
    Result Self
  invalid_length : Std.Usize → Dyn (fun _dyn => serde_core.de.Expected _dyn)
    → Result Self
  duplicate_field : Str → Result Self

/-- Trait declaration: [serde_core::de::Deserialize]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/serde_core-1.0.228/src/de/mod.rs', lines 554:0-554:33
    Name pattern: [serde_core::de::Deserialize] -/
@[rust_trait "serde_core::de::Deserialize"]
structure serde_core.de.Deserialize (Self : Type) where
  deserialize : forall {D : Type} {Clause0_Error : Type} (DeserializerInst :
    serde_core.de.Deserializer D Clause0_Error), D → Result
    (core.result.Result Self Clause0_Error)

/-- Trait declaration: [serde_core::de::DeserializeSeed]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/serde_core-1.0.228/src/de/mod.rs', lines 803:0-803:37
    Name pattern: [serde_core::de::DeserializeSeed] -/
@[rust_trait "serde_core::de::DeserializeSeed"]
structure serde_core.de.DeserializeSeed (Self : Type) (Self_Value : Type) where
  deserialize : forall {D : Type} {Clause0_Error : Type} (DeserializerInst :
    serde_core.de.Deserializer D Clause0_Error), Self → D → Result
    (core.result.Result Self_Value Clause0_Error)

/-- Trait declaration: [serde_core::de::Deserializer]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/serde_core-1.0.228/src/de/mod.rs', lines 945:0-945:34
    Name pattern: [serde_core::de::Deserializer] -/
@[rust_trait "serde_core::de::Deserializer" (parentClauses := ["ErrorInst"])]
structure serde_core.de.Deserializer (Self : Type) (Self_Error : Type) where
  ErrorInst : serde_core.de.Error Self_Error
  deserialize_any : forall {V : Type} {Clause0_Value : Type} (VisitorInst :
    serde_core.de.Visitor V Clause0_Value), Self → V → Result
    (core.result.Result Clause0_Value Self_Error)
  deserialize_bool : forall {V : Type} {Clause0_Value : Type} (VisitorInst :
    serde_core.de.Visitor V Clause0_Value), Self → V → Result
    (core.result.Result Clause0_Value Self_Error)
  deserialize_i8 : forall {V : Type} {Clause0_Value : Type} (VisitorInst :
    serde_core.de.Visitor V Clause0_Value), Self → V → Result
    (core.result.Result Clause0_Value Self_Error)
  deserialize_i16 : forall {V : Type} {Clause0_Value : Type} (VisitorInst :
    serde_core.de.Visitor V Clause0_Value), Self → V → Result
    (core.result.Result Clause0_Value Self_Error)
  deserialize_i32 : forall {V : Type} {Clause0_Value : Type} (VisitorInst :
    serde_core.de.Visitor V Clause0_Value), Self → V → Result
    (core.result.Result Clause0_Value Self_Error)
  deserialize_i64 : forall {V : Type} {Clause0_Value : Type} (VisitorInst :
    serde_core.de.Visitor V Clause0_Value), Self → V → Result
    (core.result.Result Clause0_Value Self_Error)
  deserialize_u8 : forall {V : Type} {Clause0_Value : Type} (VisitorInst :
    serde_core.de.Visitor V Clause0_Value), Self → V → Result
    (core.result.Result Clause0_Value Self_Error)
  deserialize_u16 : forall {V : Type} {Clause0_Value : Type} (VisitorInst :
    serde_core.de.Visitor V Clause0_Value), Self → V → Result
    (core.result.Result Clause0_Value Self_Error)
  deserialize_u32 : forall {V : Type} {Clause0_Value : Type} (VisitorInst :
    serde_core.de.Visitor V Clause0_Value), Self → V → Result
    (core.result.Result Clause0_Value Self_Error)
  deserialize_u64 : forall {V : Type} {Clause0_Value : Type} (VisitorInst :
    serde_core.de.Visitor V Clause0_Value), Self → V → Result
    (core.result.Result Clause0_Value Self_Error)
  deserialize_f32 : forall {V : Type} {Clause0_Value : Type} (VisitorInst :
    serde_core.de.Visitor V Clause0_Value), Self → V → Result
    (core.result.Result Clause0_Value Self_Error)
  deserialize_f64 : forall {V : Type} {Clause0_Value : Type} (VisitorInst :
    serde_core.de.Visitor V Clause0_Value), Self → V → Result
    (core.result.Result Clause0_Value Self_Error)
  deserialize_char : forall {V : Type} {Clause0_Value : Type} (VisitorInst :
    serde_core.de.Visitor V Clause0_Value), Self → V → Result
    (core.result.Result Clause0_Value Self_Error)
  deserialize_str : forall {V : Type} {Clause0_Value : Type} (VisitorInst :
    serde_core.de.Visitor V Clause0_Value), Self → V → Result
    (core.result.Result Clause0_Value Self_Error)
  deserialize_string : forall {V : Type} {Clause0_Value : Type} (VisitorInst :
    serde_core.de.Visitor V Clause0_Value), Self → V → Result
    (core.result.Result Clause0_Value Self_Error)
  deserialize_bytes : forall {V : Type} {Clause0_Value : Type} (VisitorInst :
    serde_core.de.Visitor V Clause0_Value), Self → V → Result
    (core.result.Result Clause0_Value Self_Error)
  deserialize_byte_buf : forall {V : Type} {Clause0_Value : Type} (VisitorInst
    : serde_core.de.Visitor V Clause0_Value), Self → V → Result
    (core.result.Result Clause0_Value Self_Error)
  deserialize_option : forall {V : Type} {Clause0_Value : Type} (VisitorInst :
    serde_core.de.Visitor V Clause0_Value), Self → V → Result
    (core.result.Result Clause0_Value Self_Error)
  deserialize_unit : forall {V : Type} {Clause0_Value : Type} (VisitorInst :
    serde_core.de.Visitor V Clause0_Value), Self → V → Result
    (core.result.Result Clause0_Value Self_Error)
  deserialize_unit_struct : forall {V : Type} {Clause0_Value : Type}
    (VisitorInst : serde_core.de.Visitor V Clause0_Value), Self → Str → V
    → Result (core.result.Result Clause0_Value Self_Error)
  deserialize_newtype_struct : forall {V : Type} {Clause0_Value : Type}
    (VisitorInst : serde_core.de.Visitor V Clause0_Value), Self → Str → V
    → Result (core.result.Result Clause0_Value Self_Error)
  deserialize_seq : forall {V : Type} {Clause0_Value : Type} (VisitorInst :
    serde_core.de.Visitor V Clause0_Value), Self → V → Result
    (core.result.Result Clause0_Value Self_Error)
  deserialize_tuple : forall {V : Type} {Clause0_Value : Type} (VisitorInst :
    serde_core.de.Visitor V Clause0_Value), Self → Std.Usize → V → Result
    (core.result.Result Clause0_Value Self_Error)
  deserialize_tuple_struct : forall {V : Type} {Clause0_Value : Type}
    (VisitorInst : serde_core.de.Visitor V Clause0_Value), Self → Str →
    Std.Usize → V → Result (core.result.Result Clause0_Value Self_Error)
  deserialize_map : forall {V : Type} {Clause0_Value : Type} (VisitorInst :
    serde_core.de.Visitor V Clause0_Value), Self → V → Result
    (core.result.Result Clause0_Value Self_Error)
  deserialize_struct : forall {V : Type} {Clause0_Value : Type} (VisitorInst :
    serde_core.de.Visitor V Clause0_Value), Self → Str → Slice Str → V
    → Result (core.result.Result Clause0_Value Self_Error)
  deserialize_enum : forall {V : Type} {Clause0_Value : Type} (VisitorInst :
    serde_core.de.Visitor V Clause0_Value), Self → Str → Slice Str → V
    → Result (core.result.Result Clause0_Value Self_Error)
  deserialize_identifier : forall {V : Type} {Clause0_Value : Type}
    (VisitorInst : serde_core.de.Visitor V Clause0_Value), Self → V →
    Result (core.result.Result Clause0_Value Self_Error)
  deserialize_ignored_any : forall {V : Type} {Clause0_Value : Type}
    (VisitorInst : serde_core.de.Visitor V Clause0_Value), Self → V →
    Result (core.result.Result Clause0_Value Self_Error)

/-- Trait declaration: [serde_core::de::Visitor]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/serde_core-1.0.228/src/de/mod.rs', lines 1317:0-1317:29
    Name pattern: [serde_core::de::Visitor] -/
@[rust_trait "serde_core::de::Visitor"]
structure serde_core.de.Visitor (Self : Type) (Self_Value : Type) where
  expecting : Self → core.fmt.Formatter → Result ((core.result.Result Unit
    core.fmt.Error) × core.fmt.Formatter)
  visit_u64 : forall {E : Type} (ErrorInst : serde_core.de.Error E), Self →
    Std.U64 → Result (core.result.Result Self_Value E)
  visit_str : forall {E : Type} (ErrorInst : serde_core.de.Error E), Self →
    Str → Result (core.result.Result Self_Value E)
  visit_bytes : forall {E : Type} (ErrorInst : serde_core.de.Error E), Self →
    Slice Std.U8 → Result (core.result.Result Self_Value E)
  visit_seq : forall {A : Type} {Clause0_Error : Type} (SeqAccessInst :
    serde_core.de.SeqAccess A Clause0_Error), Self → A → Result
    (core.result.Result Self_Value Clause0_Error)
  visit_map : forall {A : Type} {Clause0_Error : Type} (MapAccessInst :
    serde_core.de.MapAccess A Clause0_Error), Self → A → Result
    (core.result.Result Self_Value Clause0_Error)

/-- Trait declaration: [serde_core::de::SeqAccess]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/serde_core-1.0.228/src/de/mod.rs', lines 1749:0-1749:24
    Name pattern: [serde_core::de::SeqAccess] -/
@[rust_trait "serde_core::de::SeqAccess" (parentClauses := ["ErrorInst"])]
structure serde_core.de.SeqAccess (Self : Type) (Self_Error : Type) where
  ErrorInst : serde_core.de.Error Self_Error
  next_element_seed : forall {T : Type} {Clause0_Value : Type}
    (DeserializeSeedInst : serde_core.de.DeserializeSeed T Clause0_Value), Self
    → T → Result ((core.result.Result (Option Clause0_Value) Self_Error) ×
    Self)
  next_element : forall {T : Type} (DeserializeInst : serde_core.de.Deserialize
    T), Self → Result ((core.result.Result (Option T) Self_Error) × Self)

/-- Trait declaration: [serde_core::de::MapAccess]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/serde_core-1.0.228/src/de/mod.rs', lines 1837:0-1837:24
    Name pattern: [serde_core::de::MapAccess] -/
@[rust_trait "serde_core::de::MapAccess" (parentClauses := ["ErrorInst"])]
structure serde_core.de.MapAccess (Self : Type) (Self_Error : Type) where
  ErrorInst : serde_core.de.Error Self_Error
  next_key_seed : forall {K : Type} {Clause0_Value : Type} (DeserializeSeedInst
    : serde_core.de.DeserializeSeed K Clause0_Value), Self → K → Result
    ((core.result.Result (Option Clause0_Value) Self_Error) × Self)
  next_value_seed : forall {V : Type} {Clause0_Value : Type}
    (DeserializeSeedInst : serde_core.de.DeserializeSeed V Clause0_Value), Self
    → V → Result ((core.result.Result Clause0_Value Self_Error) × Self)
  next_key : forall {K : Type} (DeserializeInst : serde_core.de.Deserialize K),
    Self → Result ((core.result.Result (Option K) Self_Error) × Self)
  next_value : forall {V : Type} (DeserializeInst : serde_core.de.Deserialize
    V), Self → Result ((core.result.Result V Self_Error) × Self)

/-- [serde_core::de::ignored_any::IgnoredAny]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/serde_core-1.0.228/src/de/ignored_any.rs', lines 111:0-111:21
    Name pattern: [serde_core::de::ignored_any::IgnoredAny] -/
@[reducible, rust_type "serde_core::de::ignored_any::IgnoredAny"]
def serde_core.de.ignored_any.IgnoredAny := Unit

/-- Trait declaration: [serde_core::ser::Error]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/serde_core-1.0.228/src/ser/mod.rs', lines 148:8-148:48
    Name pattern: [serde_core::ser::Error] -/
@[rust_trait "serde_core::ser::Error"
  (parentClauses := ["coreerrorErrorInst"])]
structure serde_core.ser.Error (Self : Type) where
  coreerrorErrorInst : core.error.Error Self
  custom : forall {T : Type} (corefmtDisplayInst : core.fmt.Display T), T →
    Result Self

/-- Trait declaration: [serde_core::ser::Serialize]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/serde_core-1.0.228/src/ser/mod.rs', lines 234:0-234:19
    Name pattern: [serde_core::ser::Serialize] -/
@[rust_trait "serde_core::ser::Serialize"]
structure serde_core.ser.Serialize (Self : Type) where
  serialize : forall {S : Type} {Clause0_Ok : Type} {Clause0_Error : Type}
    {Clause0_SerializeSeq : Type} {Clause0_SerializeTuple : Type}
    {Clause0_SerializeTupleStruct : Type} {Clause0_SerializeTupleVariant :
    Type} {Clause0_SerializeMap : Type} {Clause0_SerializeStruct : Type}
    {Clause0_SerializeStructVariant : Type} (SerializerInst :
    serde_core.ser.Serializer S Clause0_Ok Clause0_Error Clause0_SerializeSeq
    Clause0_SerializeTuple Clause0_SerializeTupleStruct
    Clause0_SerializeTupleVariant Clause0_SerializeMap Clause0_SerializeStruct
    Clause0_SerializeStructVariant), Self → S → Result (core.result.Result
    Clause0_Ok Clause0_Error)

/-- Trait declaration: [serde_core::ser::Serializer]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/serde_core-1.0.228/src/ser/mod.rs', lines 355:0-355:27
    Name pattern: [serde_core::ser::Serializer] -/
@[rust_trait "serde_core::ser::Serializer"
  (parentClauses := ["ErrorInst", "SerializeSeqInst", "SerializeTupleInst", "SerializeTupleStructInst", "SerializeTupleVariantInst", "SerializeMapInst", "SerializeStructInst", "SerializeStructVariantInst"])]
structure serde_core.ser.Serializer (Self : Type) (Self_Ok : Type) (Self_Error
  : Type) (Self_SerializeSeq : Type) (Self_SerializeTuple : Type)
  (Self_SerializeTupleStruct : Type) (Self_SerializeTupleVariant : Type)
  (Self_SerializeMap : Type) (Self_SerializeStruct : Type)
  (Self_SerializeStructVariant : Type) where
  ErrorInst : serde_core.ser.Error Self_Error
  SerializeSeqInst : serde_core.ser.SerializeSeq Self_SerializeSeq Self_Ok
    Self_Error
  SerializeTupleInst : serde_core.ser.SerializeTuple Self_SerializeTuple
    Self_Ok Self_Error
  SerializeTupleStructInst : serde_core.ser.SerializeTupleStruct
    Self_SerializeTupleStruct Self_Ok Self_Error
  SerializeTupleVariantInst : serde_core.ser.SerializeTupleVariant
    Self_SerializeTupleVariant Self_Ok Self_Error
  SerializeMapInst : serde_core.ser.SerializeMap Self_SerializeMap Self_Ok
    Self_Error
  SerializeStructInst : serde_core.ser.SerializeStruct Self_SerializeStruct
    Self_Ok Self_Error
  SerializeStructVariantInst : serde_core.ser.SerializeStructVariant
    Self_SerializeStructVariant Self_Ok Self_Error
  serialize_bool : Self → Bool → Result (core.result.Result Self_Ok
    Self_Error)
  serialize_i8 : Self → Std.I8 → Result (core.result.Result Self_Ok
    Self_Error)
  serialize_i16 : Self → Std.I16 → Result (core.result.Result Self_Ok
    Self_Error)
  serialize_i32 : Self → Std.I32 → Result (core.result.Result Self_Ok
    Self_Error)
  serialize_i64 : Self → Std.I64 → Result (core.result.Result Self_Ok
    Self_Error)
  serialize_u8 : Self → Std.U8 → Result (core.result.Result Self_Ok
    Self_Error)
  serialize_u16 : Self → Std.U16 → Result (core.result.Result Self_Ok
    Self_Error)
  serialize_u32 : Self → Std.U32 → Result (core.result.Result Self_Ok
    Self_Error)
  serialize_u64 : Self → Std.U64 → Result (core.result.Result Self_Ok
    Self_Error)
  serialize_f32 : Self → F32 → Result (core.result.Result Self_Ok
    Self_Error)
  serialize_f64 : Self → F64 → Result (core.result.Result Self_Ok
    Self_Error)
  serialize_char : Self → Char → Result (core.result.Result Self_Ok
    Self_Error)
  serialize_str : Self → Str → Result (core.result.Result Self_Ok
    Self_Error)
  serialize_bytes : Self → Slice Std.U8 → Result (core.result.Result
    Self_Ok Self_Error)
  serialize_none : Self → Result (core.result.Result Self_Ok Self_Error)
  serialize_some : forall {T : Type} (SerializeInst : serde_core.ser.Serialize
    T), Self → T → Result (core.result.Result Self_Ok Self_Error)
  serialize_unit : Self → Result (core.result.Result Self_Ok Self_Error)
  serialize_unit_struct : Self → Str → Result (core.result.Result Self_Ok
    Self_Error)
  serialize_unit_variant : Self → Str → Std.U32 → Str → Result
    (core.result.Result Self_Ok Self_Error)
  serialize_newtype_struct : forall {T : Type} (SerializeInst :
    serde_core.ser.Serialize T), Self → Str → T → Result
    (core.result.Result Self_Ok Self_Error)
  serialize_newtype_variant : forall {T : Type} (SerializeInst :
    serde_core.ser.Serialize T), Self → Str → Std.U32 → Str → T →
    Result (core.result.Result Self_Ok Self_Error)
  serialize_seq : Self → Option Std.Usize → Result (core.result.Result
    Self_SerializeSeq Self_Error)
  serialize_tuple : Self → Std.Usize → Result (core.result.Result
    Self_SerializeTuple Self_Error)
  serialize_tuple_struct : Self → Str → Std.Usize → Result
    (core.result.Result Self_SerializeTupleStruct Self_Error)
  serialize_tuple_variant : Self → Str → Std.U32 → Str → Std.Usize →
    Result (core.result.Result Self_SerializeTupleVariant Self_Error)
  serialize_map : Self → Option Std.Usize → Result (core.result.Result
    Self_SerializeMap Self_Error)
  serialize_struct : Self → Str → Std.Usize → Result (core.result.Result
    Self_SerializeStruct Self_Error)
  serialize_struct_variant : Self → Str → Std.U32 → Str → Std.Usize →
    Result (core.result.Result Self_SerializeStructVariant Self_Error)

/-- Trait declaration: [serde_core::ser::SerializeSeq]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/serde_core-1.0.228/src/ser/mod.rs', lines 1518:0-1518:22
    Name pattern: [serde_core::ser::SerializeSeq] -/
@[rust_trait "serde_core::ser::SerializeSeq" (parentClauses := ["ErrorInst"])]
structure serde_core.ser.SerializeSeq (Self : Type) (Self_Ok : Type)
  (Self_Error : Type) where
  ErrorInst : serde_core.ser.Error Self_Error
  serialize_element : forall {T : Type} (SerializeInst :
    serde_core.ser.Serialize T), Self → T → Result ((core.result.Result
    Unit Self_Error) × Self)
  «end» : Self → Result (core.result.Result Self_Ok Self_Error)

/-- Trait declaration: [serde_core::ser::SerializeTuple]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/serde_core-1.0.228/src/ser/mod.rs', lines 1624:0-1624:24
    Name pattern: [serde_core::ser::SerializeTuple] -/
@[rust_trait "serde_core::ser::SerializeTuple"
  (parentClauses := ["ErrorInst"])]
structure serde_core.ser.SerializeTuple (Self : Type) (Self_Ok : Type)
  (Self_Error : Type) where
  ErrorInst : serde_core.ser.Error Self_Error
  serialize_element : forall {T : Type} (SerializeInst :
    serde_core.ser.Serialize T), Self → T → Result ((core.result.Result
    Unit Self_Error) × Self)
  «end» : Self → Result (core.result.Result Self_Ok Self_Error)

/-- Trait declaration: [serde_core::ser::SerializeTupleStruct]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/serde_core-1.0.228/src/ser/mod.rs', lines 1675:0-1675:30
    Name pattern: [serde_core::ser::SerializeTupleStruct] -/
@[rust_trait "serde_core::ser::SerializeTupleStruct"
  (parentClauses := ["ErrorInst"])]
structure serde_core.ser.SerializeTupleStruct (Self : Type) (Self_Ok : Type)
  (Self_Error : Type) where
  ErrorInst : serde_core.ser.Error Self_Error
  serialize_field : forall {T : Type} (SerializeInst : serde_core.ser.Serialize
    T), Self → T → Result ((core.result.Result Unit Self_Error) × Self)
  «end» : Self → Result (core.result.Result Self_Ok Self_Error)

/-- Trait declaration: [serde_core::ser::SerializeTupleVariant]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/serde_core-1.0.228/src/ser/mod.rs', lines 1739:0-1739:31
    Name pattern: [serde_core::ser::SerializeTupleVariant] -/
@[rust_trait "serde_core::ser::SerializeTupleVariant"
  (parentClauses := ["ErrorInst"])]
structure serde_core.ser.SerializeTupleVariant (Self : Type) (Self_Ok : Type)
  (Self_Error : Type) where
  ErrorInst : serde_core.ser.Error Self_Error
  serialize_field : forall {T : Type} (SerializeInst : serde_core.ser.Serialize
    T), Self → T → Result ((core.result.Result Unit Self_Error) × Self)
  «end» : Self → Result (core.result.Result Self_Ok Self_Error)

/-- Trait declaration: [serde_core::ser::SerializeMap]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/serde_core-1.0.228/src/ser/mod.rs', lines 1811:0-1811:22
    Name pattern: [serde_core::ser::SerializeMap] -/
@[rust_trait "serde_core::ser::SerializeMap" (parentClauses := ["ErrorInst"])]
structure serde_core.ser.SerializeMap (Self : Type) (Self_Ok : Type)
  (Self_Error : Type) where
  ErrorInst : serde_core.ser.Error Self_Error
  serialize_key : forall {T : Type} (SerializeInst : serde_core.ser.Serialize
    T), Self → T → Result ((core.result.Result Unit Self_Error) × Self)
  serialize_value : forall {T : Type} (SerializeInst : serde_core.ser.Serialize
    T), Self → T → Result ((core.result.Result Unit Self_Error) × Self)
  «end» : Self → Result (core.result.Result Self_Ok Self_Error)

/-- Trait declaration: [serde_core::ser::SerializeStruct]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/serde_core-1.0.228/src/ser/mod.rs', lines 1907:0-1907:25
    Name pattern: [serde_core::ser::SerializeStruct] -/
@[rust_trait "serde_core::ser::SerializeStruct"
  (parentClauses := ["ErrorInst"])]
structure serde_core.ser.SerializeStruct (Self : Type) (Self_Ok : Type)
  (Self_Error : Type) where
  ErrorInst : serde_core.ser.Error Self_Error
  serialize_field : forall {T : Type} (SerializeInst : serde_core.ser.Serialize
    T), Self → Str → T → Result ((core.result.Result Unit Self_Error) ×
    Self)
  «end» : Self → Result (core.result.Result Self_Ok Self_Error)

/-- Trait declaration: [serde_core::ser::SerializeStructVariant]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/serde_core-1.0.228/src/ser/mod.rs', lines 1977:0-1977:32
    Name pattern: [serde_core::ser::SerializeStructVariant] -/
@[rust_trait "serde_core::ser::SerializeStructVariant"
  (parentClauses := ["ErrorInst"])]
structure serde_core.ser.SerializeStructVariant (Self : Type) (Self_Ok : Type)
  (Self_Error : Type) where
  ErrorInst : serde_core.ser.Error Self_Error
  serialize_field : forall {T : Type} (SerializeInst : serde_core.ser.Serialize
    T), Self → Str → T → Result ((core.result.Result Unit Self_Error) ×
    Self)
  «end» : Self → Result (core.result.Result Self_Ok Self_Error)

/-- [hush_core::error::Error]
    Source: 'crates/libs/hush-core/src/error.rs', lines 8:0-50:1 -/
@[discriminant isize]
inductive error.Error where
| InvalidSignature : error.Error
| InvalidPublicKey : String → error.Error
| InvalidPrivateKey : error.Error
| InvalidHex : String → error.Error
| InvalidHashLength : Std.Usize → Std.Usize → error.Error
| MerkleProofFailed : error.Error
| EmptyTree : error.Error
| InvalidProofIndex : Std.Usize → Std.Usize → error.Error
| JsonError : String → error.Error
| ReceiptVerificationFailed : String → error.Error
| InvalidReceiptVersion : String → error.Error
| UnsupportedReceiptVersion : String → String → error.Error
| IoError : String → error.Error
| TpmError : String → error.Error

/-- [hush_core::merkle::MerkleTree]
    Source: 'crates/libs/hush-core/src/merkle.rs', lines 53:0-55:1 -/
structure merkle.MerkleTree where
  levels : alloc.vec.Vec (alloc.vec.Vec hashing.Hash)

/-- [hush_core::merkle::MerkleProof]
    Source: 'crates/libs/hush-core/src/merkle.rs', lines 207:0-214:1 -/
structure merkle.MerkleProof where
  tree_size : Std.Usize
  leaf_index : Std.Usize
  audit_path : alloc.vec.Vec hashing.Hash

/-- [hush_core::merkle::_#1::{serde_core::de::Deserialize<'de> for hush_core::merkle::MerkleProof}::deserialize::__Field]
    Source: 'crates/libs/hush-core/src/merkle.rs', lines 206:34-206:45 -/
@[discriminant isize]
inductive merkle.__1.DeserializeDeMerkleProof.deserialize.__Field where
| __field0 : merkle.__1.DeserializeDeMerkleProof.deserialize.__Field
| __field1 : merkle.__1.DeserializeDeMerkleProof.deserialize.__Field
| __field2 : merkle.__1.DeserializeDeMerkleProof.deserialize.__Field
| __ignore : merkle.__1.DeserializeDeMerkleProof.deserialize.__Field

/-- [hush_core::merkle::_#1::{serde_core::de::Deserialize<'de> for hush_core::merkle::MerkleProof}::deserialize::__FieldVisitor]
    Source: 'crates/libs/hush-core/src/merkle.rs', lines 206:34-206:45 -/
@[reducible]
def merkle.__1.DeserializeDeMerkleProof.deserialize.__FieldVisitor := Unit

/-- [hush_core::merkle::_#1::{serde_core::de::Deserialize<'de> for hush_core::merkle::MerkleProof}::deserialize::__Visitor]
    Source: 'crates/libs/hush-core/src/merkle.rs', lines 206:34-206:45 -/
structure merkle.__1.DeserializeDeMerkleProof.deserialize.__Visitor where
  marker : core.marker.PhantomData merkle.MerkleProof
  lifetime : core.marker.PhantomData Unit

end hush_core
